// Code generated by goquent typed repository; DO NOT EDIT.
// Code generated by goquent typed-repository-v2; DO NOT EDIT.
// Snapshot kind: manifest; supplied declarations only, not live identity or authorization.
// Schema fingerprint: "sha256:0252aee004c8b7eca19f67c9792ce56c12f5be7f1ed4dcd8558d77cb25ed4b32"
// Policy fingerprint: "sha256:e6f00857161b828e6c6e1fd24eaff572c81b53d0cc5ce918d2c01d96158d7a27"
package typedfixture

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"

	"github.com/recoweft/goquent/orm"
	"github.com/recoweft/goquent/orm/manifest"
	"github.com/recoweft/goquent/orm/operation"
)

type MySQLTenantRecordRow struct {
	Active   bool  `db:"active"`
	ID       int64 `db:"id,pk"`
	TenantID int64 `db:"tenant_id,pk"`
}

func (MySQLTenantRecordRow) TableName() string { return "gq08_tenants" }

type MySQLTenantRecordRepository struct {
	db *orm.DB
}

func NewMySQLTenantRecordRepository(db *orm.DB) *MySQLTenantRecordRepository {
	return &MySQLTenantRecordRepository{db: db}
}

// MySQLTenantRecordPatch has independent, nominal column states. Its zero value changes nothing.
type MySQLTenantRecordPatch struct {
	Active MySQLTenantRecordActivePatch
}

func (MySQLTenantRecordPatch) String() string { return "goquent: generated details omitted" }
func (MySQLTenantRecordPatch) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLTenantRecordPatch) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}

type MySQLTenantRecordActivePatch struct {
	state uint8
	value bool
}

func (MySQLTenantRecordActivePatch) String() string { return "goquent: generated details omitted" }
func (MySQLTenantRecordActivePatch) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLTenantRecordActivePatch) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c MySQLTenantRecordActiveColumn) Set(value bool) MySQLTenantRecordActivePatch {
	if !c.valid {
		return MySQLTenantRecordActivePatch{state: 3}
	}
	return MySQLTenantRecordActivePatch{state: 1, value: bool(value)}
}

// MySQLTenantRecordUpdate adds predicates without introducing write limits or ordering.
type MySQLTenantRecordUpdate struct {
	Filters      []MySQLTenantRecordPredicate
	AccessReason string
}

func (MySQLTenantRecordUpdate) String() string { return "goquent: generated details omitted" }
func (MySQLTenantRecordUpdate) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLTenantRecordUpdate) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (in MySQLTenantRecordUpdate) spec(patch MySQLTenantRecordPatch, returning []string) operation.UpdateSpec {
	s := operation.UpdateSpec{Version: 1, Model: "gq08_tenants", Returning: returning, AccessReason: in.AccessReason}
	for _, f := range in.Filters {
		s.Filters = append(s.Filters, f.filter)
	}
	if patch.Active.state != 0 {
		a := operation.UpdateAssignment{Column: "active"}
		switch patch.Active.state {
		case 1:
			a.State = operation.UpdateValue
			a.Value = patch.Active.value
			a.ValuePresent = true
		case 2:
			a.State = operation.UpdateNull
		default:
			a.State = operation.UpdateState("invalid")
		}
		s.Assignments = append(s.Assignments, a)
	}
	return s
}
func (r *MySQLTenantRecordRepository) PlanUpdateByKey(ctx context.Context, key MySQLTenantRecordKey, patch MySQLTenantRecordPatch, input MySQLTenantRecordUpdate) (*orm.QueryPlan, operation.DiagnosticView, error) {
	input.Filters = mySQLTenantRecordKeyInput(key, MySQLTenantRecordRead{Filters: input.Filters}).Filters
	return r.db.CompileUpdateWithDiagnostics(ctx, input.spec(patch, nil), operation.Options{Manifest: mySQLTenantRecordSnapshot()})
}
func (r *MySQLTenantRecordRepository) UpdateByKey(ctx context.Context, key MySQLTenantRecordKey, patch MySQLTenantRecordPatch, input MySQLTenantRecordUpdate) (sql.Result, error) {
	input.Filters = mySQLTenantRecordKeyInput(key, MySQLTenantRecordRead{Filters: input.Filters}).Filters
	return orm.UpdateOperationBy(ctx, r.db, input.spec(patch, nil), operation.Options{Manifest: mySQLTenantRecordSnapshot()})
}
func (r *MySQLTenantRecordRepository) PlanUpdateIdentityByKey(ctx context.Context, key MySQLTenantRecordKey, patch MySQLTenantRecordPatch, input MySQLTenantRecordUpdate) (*orm.QueryPlan, operation.DiagnosticView, error) {
	input.Filters = mySQLTenantRecordKeyInput(key, MySQLTenantRecordRead{Filters: input.Filters}).Filters
	return r.db.CompileUpdateWithDiagnostics(ctx, input.spec(patch, []string{"id", "tenant_id", "active"}), operation.Options{Manifest: mySQLTenantRecordSnapshot()})
}
func (r *MySQLTenantRecordRepository) UpdateIdentityByKey(ctx context.Context, key MySQLTenantRecordKey, patch MySQLTenantRecordPatch, input MySQLTenantRecordUpdate) (MySQLTenantRecordIdentityRow, error) {
	input.Filters = mySQLTenantRecordKeyInput(key, MySQLTenantRecordRead{Filters: input.Filters}).Filters
	return orm.UpdateOperationReturningBy[MySQLTenantRecordIdentityRow](ctx, r.db, input.spec(patch, []string{"id", "tenant_id", "active"}), operation.Options{Manifest: mySQLTenantRecordSnapshot()})
}
func (MySQLTenantRecordRow) String() string { return "goquent: generated details omitted" }
func (MySQLTenantRecordRow) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLTenantRecordRow) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (MySQLTenantRecordRepository) String() string { return "goquent: generated details omitted" }
func (MySQLTenantRecordRepository) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLTenantRecordRepository) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}

type MySQLTenantRecordPredicate struct{ filter operation.FilterSpec }
type MySQLTenantRecordOrder struct{ order operation.OrderSpec }

// MySQLTenantRecordRead carries typed filters and ordering. Runtime validation still applies.
type MySQLTenantRecordRead struct {
	Filters      []MySQLTenantRecordPredicate
	OrderBy      []MySQLTenantRecordOrder
	Limit        *int64
	AccessReason string
}

func (MySQLTenantRecordPredicate) String() string { return "goquent: generated details omitted" }
func (MySQLTenantRecordPredicate) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLTenantRecordPredicate) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (MySQLTenantRecordOrder) String() string { return "goquent: generated details omitted" }
func (MySQLTenantRecordOrder) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLTenantRecordOrder) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (MySQLTenantRecordRead) String() string { return "goquent: generated details omitted" }
func (MySQLTenantRecordRead) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLTenantRecordRead) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func mySQLTenantRecordSnapshot() *manifest.Manifest {
	var m manifest.Manifest
	_ = json.Unmarshal([]byte("{\"version\":\"1\",\"generated_at\":\"1970-01-01T00:00:01Z\",\"generator_version\":\"fixture\",\"dialect\":\"mysql\",\"schema_fingerprint\":\"sha256:0252aee004c8b7eca19f67c9792ce56c12f5be7f1ed4dcd8558d77cb25ed4b32\",\"policy_fingerprint\":\"sha256:e6f00857161b828e6c6e1fd24eaff572c81b53d0cc5ce918d2c01d96158d7a27\",\"tables\":[{\"name\":\"gq08_tenants\",\"columns\":[{\"name\":\"active\",\"type\":\"boolean\",\"type_source\":\"sql\",\"nullable\":false},{\"name\":\"id\",\"type\":\"bigint\",\"type_source\":\"sql\",\"primary\":true,\"nullable\":false},{\"name\":\"tenant_id\",\"type\":\"bigint\",\"type_source\":\"sql\",\"primary\":true,\"nullable\":false,\"tenant_scope\":true,\"required_filter\":true}]}]}"), &m)
	return &m
}
func (in MySQLTenantRecordRead) spec(columns []string) operation.OperationSpec {
	s := operation.OperationSpec{Version: 1, Operation: "select", Model: "gq08_tenants", Select: columns, AccessReason: in.AccessReason}
	if in.Limit != nil {
		n := *in.Limit
		s.Limit = &n
	}
	for _, f := range in.Filters {
		s.Filters = append(s.Filters, f.filter)
	}
	for _, o := range in.OrderBy {
		s.OrderBy = append(s.OrderBy, o.order)
	}
	return s
}

type MySQLTenantRecordColumnSet struct {
	Active   MySQLTenantRecordActiveColumn
	ID       MySQLTenantRecordIDColumn
	TenantID MySQLTenantRecordTenantIDColumn
}

func (MySQLTenantRecordColumnSet) String() string { return "goquent: generated details omitted" }
func (MySQLTenantRecordColumnSet) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLTenantRecordColumnSet) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func MySQLTenantRecordColumns() MySQLTenantRecordColumnSet {
	return MySQLTenantRecordColumnSet{Active: MySQLTenantRecordActiveColumn{valid: true}, ID: MySQLTenantRecordIDColumn{valid: true}, TenantID: MySQLTenantRecordTenantIDColumn{valid: true}}
}

type MySQLTenantRecordActiveColumn struct{ valid bool }

func (MySQLTenantRecordActiveColumn) String() string { return "goquent: generated details omitted" }
func (MySQLTenantRecordActiveColumn) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLTenantRecordActiveColumn) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c MySQLTenantRecordActiveColumn) predicate(op string, value any, ref string) MySQLTenantRecordPredicate {
	if !c.valid {
		return MySQLTenantRecordPredicate{}
	}
	return MySQLTenantRecordPredicate{filter: operation.FilterSpec{Field: "active", Op: op, Value: value, ValueRef: ref}}
}
func (c MySQLTenantRecordActiveColumn) Asc() MySQLTenantRecordOrder {
	if !c.valid {
		return MySQLTenantRecordOrder{}
	}
	return MySQLTenantRecordOrder{order: operation.OrderSpec{Field: "active", Direction: "asc"}}
}
func (c MySQLTenantRecordActiveColumn) Desc() MySQLTenantRecordOrder {
	if !c.valid {
		return MySQLTenantRecordOrder{}
	}
	return MySQLTenantRecordOrder{order: operation.OrderSpec{Field: "active", Direction: "desc"}}
}
func (c MySQLTenantRecordActiveColumn) IsNull() MySQLTenantRecordPredicate {
	return c.predicate("is_null", nil, "")
}
func (c MySQLTenantRecordActiveColumn) IsNotNull() MySQLTenantRecordPredicate {
	return c.predicate("is_not_null", nil, "")
}
func (c MySQLTenantRecordActiveColumn) Eq(value bool) MySQLTenantRecordPredicate {
	return c.predicate("=", bool(value), "")
}
func (c MySQLTenantRecordActiveColumn) Ne(value bool) MySQLTenantRecordPredicate {
	return c.predicate("!=", bool(value), "")
}
func (c MySQLTenantRecordActiveColumn) In(values ...bool) MySQLTenantRecordPredicate {
	args := make([]any, len(values))
	for i, v := range values {
		args[i] = bool(v)
	}
	return c.predicate("in", args, "")
}

type MySQLTenantRecordIDKey int64

func (MySQLTenantRecordIDKey) String() string { return "goquent: generated details omitted" }
func (MySQLTenantRecordIDKey) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLTenantRecordIDKey) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}

type MySQLTenantRecordIDColumn struct{ valid bool }

func (MySQLTenantRecordIDColumn) String() string { return "goquent: generated details omitted" }
func (MySQLTenantRecordIDColumn) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLTenantRecordIDColumn) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c MySQLTenantRecordIDColumn) predicate(op string, value any, ref string) MySQLTenantRecordPredicate {
	if !c.valid {
		return MySQLTenantRecordPredicate{}
	}
	return MySQLTenantRecordPredicate{filter: operation.FilterSpec{Field: "id", Op: op, Value: value, ValueRef: ref}}
}
func (c MySQLTenantRecordIDColumn) Asc() MySQLTenantRecordOrder {
	if !c.valid {
		return MySQLTenantRecordOrder{}
	}
	return MySQLTenantRecordOrder{order: operation.OrderSpec{Field: "id", Direction: "asc"}}
}
func (c MySQLTenantRecordIDColumn) Desc() MySQLTenantRecordOrder {
	if !c.valid {
		return MySQLTenantRecordOrder{}
	}
	return MySQLTenantRecordOrder{order: operation.OrderSpec{Field: "id", Direction: "desc"}}
}
func (c MySQLTenantRecordIDColumn) IsNull() MySQLTenantRecordPredicate {
	return c.predicate("is_null", nil, "")
}
func (c MySQLTenantRecordIDColumn) IsNotNull() MySQLTenantRecordPredicate {
	return c.predicate("is_not_null", nil, "")
}
func (c MySQLTenantRecordIDColumn) Eq(value MySQLTenantRecordIDKey) MySQLTenantRecordPredicate {
	return c.predicate("=", int64(value), "")
}
func (c MySQLTenantRecordIDColumn) Ne(value MySQLTenantRecordIDKey) MySQLTenantRecordPredicate {
	return c.predicate("!=", int64(value), "")
}
func (c MySQLTenantRecordIDColumn) Lt(value MySQLTenantRecordIDKey) MySQLTenantRecordPredicate {
	return c.predicate("<", int64(value), "")
}
func (c MySQLTenantRecordIDColumn) Le(value MySQLTenantRecordIDKey) MySQLTenantRecordPredicate {
	return c.predicate("<=", int64(value), "")
}
func (c MySQLTenantRecordIDColumn) Gt(value MySQLTenantRecordIDKey) MySQLTenantRecordPredicate {
	return c.predicate(">", int64(value), "")
}
func (c MySQLTenantRecordIDColumn) Ge(value MySQLTenantRecordIDKey) MySQLTenantRecordPredicate {
	return c.predicate(">=", int64(value), "")
}
func (c MySQLTenantRecordIDColumn) In(values ...MySQLTenantRecordIDKey) MySQLTenantRecordPredicate {
	args := make([]any, len(values))
	for i, v := range values {
		args[i] = int64(v)
	}
	return c.predicate("in", args, "")
}

type MySQLTenantRecordTenantIDKey struct{ present bool }

func MySQLTenantRecordCurrentTenantKey() MySQLTenantRecordTenantIDKey {
	return MySQLTenantRecordTenantIDKey{present: true}
}
func (MySQLTenantRecordTenantIDKey) String() string { return "goquent: generated details omitted" }
func (MySQLTenantRecordTenantIDKey) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLTenantRecordTenantIDKey) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}

type MySQLTenantRecordTenantIDColumn struct{ valid bool }

func (MySQLTenantRecordTenantIDColumn) String() string { return "goquent: generated details omitted" }
func (MySQLTenantRecordTenantIDColumn) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLTenantRecordTenantIDColumn) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c MySQLTenantRecordTenantIDColumn) predicate(op string, value any, ref string) MySQLTenantRecordPredicate {
	if !c.valid {
		return MySQLTenantRecordPredicate{}
	}
	return MySQLTenantRecordPredicate{filter: operation.FilterSpec{Field: "tenant_id", Op: op, Value: value, ValueRef: ref}}
}
func (c MySQLTenantRecordTenantIDColumn) Asc() MySQLTenantRecordOrder {
	if !c.valid {
		return MySQLTenantRecordOrder{}
	}
	return MySQLTenantRecordOrder{order: operation.OrderSpec{Field: "tenant_id", Direction: "asc"}}
}
func (c MySQLTenantRecordTenantIDColumn) Desc() MySQLTenantRecordOrder {
	if !c.valid {
		return MySQLTenantRecordOrder{}
	}
	return MySQLTenantRecordOrder{order: operation.OrderSpec{Field: "tenant_id", Direction: "desc"}}
}
func (c MySQLTenantRecordTenantIDColumn) CurrentTenant() MySQLTenantRecordPredicate {
	return c.predicate("=", nil, "current_tenant")
}

type MySQLTenantRecordIdentityRow struct {
	ID       int64 `db:"id"`
	TenantID int64 `db:"tenant_id"`
	Active   bool  `db:"active"`
}

func (MySQLTenantRecordIdentityRow) String() string { return "goquent: generated details omitted" }
func (MySQLTenantRecordIdentityRow) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLTenantRecordIdentityRow) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (r *MySQLTenantRecordRepository) PlanIdentity(ctx context.Context, input MySQLTenantRecordRead) (*orm.QueryPlan, operation.DiagnosticView, error) {
	return r.db.CompileOperationWithDiagnostics(ctx, input.spec([]string{"id", "tenant_id", "active"}), operation.Options{Manifest: mySQLTenantRecordSnapshot()})
}
func (r *MySQLTenantRecordRepository) SelectIdentity(ctx context.Context, input MySQLTenantRecordRead) ([]MySQLTenantRecordIdentityRow, error) {
	return orm.SelectOperationBy[MySQLTenantRecordIdentityRow](ctx, r.db, input.spec([]string{"id", "tenant_id", "active"}), operation.Options{Manifest: mySQLTenantRecordSnapshot()})
}

type MySQLTenantRecordKey struct {
	ID       MySQLTenantRecordIDKey
	TenantID MySQLTenantRecordTenantIDKey
}

func (MySQLTenantRecordKey) String() string { return "goquent: generated details omitted" }
func (MySQLTenantRecordKey) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLTenantRecordKey) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func mySQLTenantRecordKeyInput(key MySQLTenantRecordKey, input MySQLTenantRecordRead) MySQLTenantRecordRead {
	input.Filters = append([]MySQLTenantRecordPredicate(nil), input.Filters...)
	cols := MySQLTenantRecordColumns()
	input.Filters = append(input.Filters, cols.ID.Eq(key.ID))
	if key.TenantID.present {
		input.Filters = append(input.Filters, cols.TenantID.CurrentTenant())
	} else {
		input.Filters = append(input.Filters, MySQLTenantRecordPredicate{})
	}
	return input
}
func (r *MySQLTenantRecordRepository) PlanFindByKey(ctx context.Context, key MySQLTenantRecordKey, input MySQLTenantRecordRead) (*orm.QueryPlan, operation.DiagnosticView, error) {
	input = mySQLTenantRecordKeyInput(key, input)
	return r.db.CompileOperationWithDiagnostics(ctx, input.spec([]string{"active", "id", "tenant_id"}), operation.Options{Manifest: mySQLTenantRecordSnapshot()})
}
func (r *MySQLTenantRecordRepository) FindByKey(ctx context.Context, key MySQLTenantRecordKey, input MySQLTenantRecordRead) (MySQLTenantRecordRow, error) {
	input = mySQLTenantRecordKeyInput(key, input)
	rows, err := orm.SelectOperationBy[MySQLTenantRecordRow](ctx, r.db, input.spec([]string{"active", "id", "tenant_id"}), operation.Options{Manifest: mySQLTenantRecordSnapshot()})
	if err != nil {
		return MySQLTenantRecordRow{}, err
	}
	if len(rows) == 0 {
		return MySQLTenantRecordRow{}, orm.ErrNotFound
	}
	return rows[0], nil
}
