// Code generated by goquent typed-repository-v1; DO NOT EDIT.
// Snapshot kind: manifest; supplied declarations only, not live identity or authorization.
// Schema fingerprint: "fictional-schema"
// Policy fingerprint: "fictional-policy"
package typedfixture

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"time"

	"github.com/recoweft/goquent/orm"
	"github.com/recoweft/goquent/orm/manifest"
	"github.com/recoweft/goquent/orm/operation"
)

type MySQLRecordRow struct {
	Active    bool                `db:"active"`
	Balance   string              `db:"balance"`
	Clock     MySQLRecordTimeText `db:"clock"`
	Computed  int32               `db:"computed,readonly"`
	Flag      sql.NullBool        `db:"flag"`
	Happened  time.Time           `db:"happened"`
	Hidden    string              `db:"hidden"`
	ID        int64               `db:"id,pk"`
	Immutable string              `db:"immutable,readonly"`
	Note      sql.Null[string]    `db:"note"`
	Segment   int32               `db:"segment,pk"`
	Stamp     time.Time           `db:"stamp"`
	Status    string              `db:"status"`
}

func (MySQLRecordRow) TableName() string { return "gq08_records" }

type MySQLRecordRepository struct {
	db *orm.DB
}

func NewMySQLRecordRepository(db *orm.DB) *MySQLRecordRepository {
	return &MySQLRecordRepository{db: db}
}

// MySQLRecordTimeText scans the built-in drivers' clock results without a driver argument adapter.
type MySQLRecordTimeText string

func (v *MySQLRecordTimeText) Scan(source any) error {
	switch x := source.(type) {
	case string:
		*v = MySQLRecordTimeText(x)
	case []byte:
		*v = MySQLRecordTimeText(string(x))
	case time.Time:
		if x.Year() != 0 || x.Month() != time.January || x.Day() != 1 {
			return fmt.Errorf("goquent: clock result is unsupported")
		}
		*v = MySQLRecordTimeText(x.Format("15:04:05.999999999"))
	default:
		return fmt.Errorf("goquent: clock result is unsupported")
	}
	return nil
}
func (MySQLRecordTimeText) String() string { return "goquent: generated details omitted" }
func (MySQLRecordTimeText) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLRecordTimeText) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (MySQLRecordRow) String() string { return "goquent: generated details omitted" }
func (MySQLRecordRow) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLRecordRow) MarshalJSON() ([]byte, error) { return []byte("{\"details_omitted\":true}"), nil }
func (MySQLRecordRepository) String() string        { return "goquent: generated details omitted" }
func (MySQLRecordRepository) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLRecordRepository) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}

type MySQLRecordPredicate struct{ filter operation.FilterSpec }
type MySQLRecordOrder struct{ order operation.OrderSpec }

// MySQLRecordRead carries typed filters and ordering. Runtime validation still applies.
type MySQLRecordRead struct {
	Filters      []MySQLRecordPredicate
	OrderBy      []MySQLRecordOrder
	Limit        *int64
	AccessReason string
}

func (MySQLRecordPredicate) String() string { return "goquent: generated details omitted" }
func (MySQLRecordPredicate) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLRecordPredicate) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (MySQLRecordOrder) String() string { return "goquent: generated details omitted" }
func (MySQLRecordOrder) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLRecordOrder) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (MySQLRecordRead) String() string { return "goquent: generated details omitted" }
func (MySQLRecordRead) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLRecordRead) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func mySQLRecordSnapshot() *manifest.Manifest {
	var m manifest.Manifest
	_ = json.Unmarshal([]byte("{\"version\":\"1\",\"generated_at\":\"1970-01-01T00:00:01Z\",\"generator_version\":\"fixture\",\"dialect\":\"mysql\",\"schema_fingerprint\":\"fictional-schema\",\"policy_fingerprint\":\"fictional-policy\",\"tables\":[{\"name\":\"gq08_records\",\"columns\":[{\"name\":\"id\",\"type\":\"bigint\",\"type_source\":\"sql\",\"primary\":true,\"nullable\":false},{\"name\":\"segment\",\"type\":\"integer\",\"type_source\":\"sql\",\"primary\":true,\"nullable\":false},{\"name\":\"status\",\"type\":\"varchar(12)\",\"type_source\":\"sql\",\"nullable\":false,\"enum_values\":[\"ready\",\"closed\",\"a-b\",\"a_b\",\"type\"]},{\"name\":\"active\",\"type\":\"boolean\",\"type_source\":\"sql\",\"nullable\":false},{\"name\":\"flag\",\"type\":\"boolean\",\"type_source\":\"sql\",\"nullable\":true},{\"name\":\"note\",\"type\":\"text\",\"type_source\":\"sql\",\"nullable\":true},{\"name\":\"balance\",\"type\":\"decimal(30,4)\",\"type_source\":\"sql\",\"nullable\":false},{\"name\":\"happened\",\"type\":\"date\",\"type_source\":\"sql\",\"nullable\":false},{\"name\":\"clock\",\"type\":\"time(6)\",\"type_source\":\"sql\",\"nullable\":false},{\"name\":\"stamp\",\"type\":\"datetime(6)\",\"type_source\":\"sql\",\"nullable\":false},{\"name\":\"immutable\",\"type\":\"text\",\"type_source\":\"sql\",\"nullable\":false,\"readonly\":true},{\"name\":\"computed\",\"type\":\"integer\",\"type_source\":\"sql\",\"nullable\":false,\"generated\":true},{\"name\":\"hidden\",\"type\":\"text\",\"type_source\":\"sql\",\"nullable\":false,\"forbidden\":true}]}]}"), &m)
	return &m
}
func (in MySQLRecordRead) spec(columns []string) operation.OperationSpec {
	s := operation.OperationSpec{Version: 1, Operation: "select", Model: "gq08_records", Select: columns, AccessReason: in.AccessReason}
	if in.Limit != nil {
		n := *in.Limit
		s.Limit = &n
	}
	for _, f := range in.Filters {
		s.Filters = append(s.Filters, f.filter)
	}
	for _, o := range in.OrderBy {
		s.OrderBy = append(s.OrderBy, o.order)
	}
	return s
}

type MySQLRecordColumnSet struct {
	Active    MySQLRecordActiveColumn
	Balance   MySQLRecordBalanceColumn
	Clock     MySQLRecordClockColumn
	Computed  MySQLRecordComputedColumn
	Flag      MySQLRecordFlagColumn
	Happened  MySQLRecordHappenedColumn
	ID        MySQLRecordIDColumn
	Immutable MySQLRecordImmutableColumn
	Note      MySQLRecordNoteColumn
	Segment   MySQLRecordSegmentColumn
	Stamp     MySQLRecordStampColumn
	Status    MySQLRecordStatusColumn
}

func (MySQLRecordColumnSet) String() string { return "goquent: generated details omitted" }
func (MySQLRecordColumnSet) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLRecordColumnSet) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func MySQLRecordColumns() MySQLRecordColumnSet {
	return MySQLRecordColumnSet{Active: MySQLRecordActiveColumn{valid: true}, Balance: MySQLRecordBalanceColumn{valid: true}, Clock: MySQLRecordClockColumn{valid: true}, Computed: MySQLRecordComputedColumn{valid: true}, Flag: MySQLRecordFlagColumn{valid: true}, Happened: MySQLRecordHappenedColumn{valid: true}, ID: MySQLRecordIDColumn{valid: true}, Immutable: MySQLRecordImmutableColumn{valid: true}, Note: MySQLRecordNoteColumn{valid: true}, Segment: MySQLRecordSegmentColumn{valid: true}, Stamp: MySQLRecordStampColumn{valid: true}, Status: MySQLRecordStatusColumn{valid: true}}
}

type MySQLRecordActiveColumn struct{ valid bool }

func (MySQLRecordActiveColumn) String() string { return "goquent: generated details omitted" }
func (MySQLRecordActiveColumn) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLRecordActiveColumn) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c MySQLRecordActiveColumn) predicate(op string, value any, ref string) MySQLRecordPredicate {
	if !c.valid {
		return MySQLRecordPredicate{}
	}
	return MySQLRecordPredicate{filter: operation.FilterSpec{Field: "active", Op: op, Value: value, ValueRef: ref}}
}
func (c MySQLRecordActiveColumn) Asc() MySQLRecordOrder {
	if !c.valid {
		return MySQLRecordOrder{}
	}
	return MySQLRecordOrder{order: operation.OrderSpec{Field: "active", Direction: "asc"}}
}
func (c MySQLRecordActiveColumn) Desc() MySQLRecordOrder {
	if !c.valid {
		return MySQLRecordOrder{}
	}
	return MySQLRecordOrder{order: operation.OrderSpec{Field: "active", Direction: "desc"}}
}
func (c MySQLRecordActiveColumn) IsNull() MySQLRecordPredicate {
	return c.predicate("is_null", nil, "")
}
func (c MySQLRecordActiveColumn) IsNotNull() MySQLRecordPredicate {
	return c.predicate("is_not_null", nil, "")
}
func (c MySQLRecordActiveColumn) Eq(value bool) MySQLRecordPredicate {
	return c.predicate("=", bool(value), "")
}
func (c MySQLRecordActiveColumn) Ne(value bool) MySQLRecordPredicate {
	return c.predicate("!=", bool(value), "")
}
func (c MySQLRecordActiveColumn) In(values ...bool) MySQLRecordPredicate {
	args := make([]any, len(values))
	for i, v := range values {
		args[i] = bool(v)
	}
	return c.predicate("in", args, "")
}

type MySQLRecordBalanceColumn struct{ valid bool }

func (MySQLRecordBalanceColumn) String() string { return "goquent: generated details omitted" }
func (MySQLRecordBalanceColumn) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLRecordBalanceColumn) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c MySQLRecordBalanceColumn) predicate(op string, value any, ref string) MySQLRecordPredicate {
	if !c.valid {
		return MySQLRecordPredicate{}
	}
	return MySQLRecordPredicate{filter: operation.FilterSpec{Field: "balance", Op: op, Value: value, ValueRef: ref}}
}
func (c MySQLRecordBalanceColumn) Asc() MySQLRecordOrder {
	if !c.valid {
		return MySQLRecordOrder{}
	}
	return MySQLRecordOrder{order: operation.OrderSpec{Field: "balance", Direction: "asc"}}
}
func (c MySQLRecordBalanceColumn) Desc() MySQLRecordOrder {
	if !c.valid {
		return MySQLRecordOrder{}
	}
	return MySQLRecordOrder{order: operation.OrderSpec{Field: "balance", Direction: "desc"}}
}
func (c MySQLRecordBalanceColumn) IsNull() MySQLRecordPredicate {
	return c.predicate("is_null", nil, "")
}
func (c MySQLRecordBalanceColumn) IsNotNull() MySQLRecordPredicate {
	return c.predicate("is_not_null", nil, "")
}
func (c MySQLRecordBalanceColumn) Eq(value json.Number) MySQLRecordPredicate {
	return c.predicate("=", json.Number(value), "")
}
func (c MySQLRecordBalanceColumn) Ne(value json.Number) MySQLRecordPredicate {
	return c.predicate("!=", json.Number(value), "")
}
func (c MySQLRecordBalanceColumn) Lt(value json.Number) MySQLRecordPredicate {
	return c.predicate("<", json.Number(value), "")
}
func (c MySQLRecordBalanceColumn) Le(value json.Number) MySQLRecordPredicate {
	return c.predicate("<=", json.Number(value), "")
}
func (c MySQLRecordBalanceColumn) Gt(value json.Number) MySQLRecordPredicate {
	return c.predicate(">", json.Number(value), "")
}
func (c MySQLRecordBalanceColumn) Ge(value json.Number) MySQLRecordPredicate {
	return c.predicate(">=", json.Number(value), "")
}
func (c MySQLRecordBalanceColumn) In(values ...json.Number) MySQLRecordPredicate {
	args := make([]any, len(values))
	for i, v := range values {
		args[i] = json.Number(v)
	}
	return c.predicate("in", args, "")
}

type MySQLRecordClockColumn struct{ valid bool }

func (MySQLRecordClockColumn) String() string { return "goquent: generated details omitted" }
func (MySQLRecordClockColumn) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLRecordClockColumn) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c MySQLRecordClockColumn) predicate(op string, value any, ref string) MySQLRecordPredicate {
	if !c.valid {
		return MySQLRecordPredicate{}
	}
	return MySQLRecordPredicate{filter: operation.FilterSpec{Field: "clock", Op: op, Value: value, ValueRef: ref}}
}
func (c MySQLRecordClockColumn) Asc() MySQLRecordOrder {
	if !c.valid {
		return MySQLRecordOrder{}
	}
	return MySQLRecordOrder{order: operation.OrderSpec{Field: "clock", Direction: "asc"}}
}
func (c MySQLRecordClockColumn) Desc() MySQLRecordOrder {
	if !c.valid {
		return MySQLRecordOrder{}
	}
	return MySQLRecordOrder{order: operation.OrderSpec{Field: "clock", Direction: "desc"}}
}
func (c MySQLRecordClockColumn) IsNull() MySQLRecordPredicate { return c.predicate("is_null", nil, "") }
func (c MySQLRecordClockColumn) IsNotNull() MySQLRecordPredicate {
	return c.predicate("is_not_null", nil, "")
}
func (c MySQLRecordClockColumn) Eq(value string) MySQLRecordPredicate {
	return c.predicate("=", string(value), "")
}
func (c MySQLRecordClockColumn) Ne(value string) MySQLRecordPredicate {
	return c.predicate("!=", string(value), "")
}
func (c MySQLRecordClockColumn) Lt(value string) MySQLRecordPredicate {
	return c.predicate("<", string(value), "")
}
func (c MySQLRecordClockColumn) Le(value string) MySQLRecordPredicate {
	return c.predicate("<=", string(value), "")
}
func (c MySQLRecordClockColumn) Gt(value string) MySQLRecordPredicate {
	return c.predicate(">", string(value), "")
}
func (c MySQLRecordClockColumn) Ge(value string) MySQLRecordPredicate {
	return c.predicate(">=", string(value), "")
}
func (c MySQLRecordClockColumn) In(values ...string) MySQLRecordPredicate {
	args := make([]any, len(values))
	for i, v := range values {
		args[i] = string(v)
	}
	return c.predicate("in", args, "")
}

type MySQLRecordComputedColumn struct{ valid bool }

func (MySQLRecordComputedColumn) String() string { return "goquent: generated details omitted" }
func (MySQLRecordComputedColumn) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLRecordComputedColumn) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c MySQLRecordComputedColumn) predicate(op string, value any, ref string) MySQLRecordPredicate {
	if !c.valid {
		return MySQLRecordPredicate{}
	}
	return MySQLRecordPredicate{filter: operation.FilterSpec{Field: "computed", Op: op, Value: value, ValueRef: ref}}
}
func (c MySQLRecordComputedColumn) Asc() MySQLRecordOrder {
	if !c.valid {
		return MySQLRecordOrder{}
	}
	return MySQLRecordOrder{order: operation.OrderSpec{Field: "computed", Direction: "asc"}}
}
func (c MySQLRecordComputedColumn) Desc() MySQLRecordOrder {
	if !c.valid {
		return MySQLRecordOrder{}
	}
	return MySQLRecordOrder{order: operation.OrderSpec{Field: "computed", Direction: "desc"}}
}
func (c MySQLRecordComputedColumn) IsNull() MySQLRecordPredicate {
	return c.predicate("is_null", nil, "")
}
func (c MySQLRecordComputedColumn) IsNotNull() MySQLRecordPredicate {
	return c.predicate("is_not_null", nil, "")
}
func (c MySQLRecordComputedColumn) Eq(value int32) MySQLRecordPredicate {
	return c.predicate("=", int32(value), "")
}
func (c MySQLRecordComputedColumn) Ne(value int32) MySQLRecordPredicate {
	return c.predicate("!=", int32(value), "")
}
func (c MySQLRecordComputedColumn) Lt(value int32) MySQLRecordPredicate {
	return c.predicate("<", int32(value), "")
}
func (c MySQLRecordComputedColumn) Le(value int32) MySQLRecordPredicate {
	return c.predicate("<=", int32(value), "")
}
func (c MySQLRecordComputedColumn) Gt(value int32) MySQLRecordPredicate {
	return c.predicate(">", int32(value), "")
}
func (c MySQLRecordComputedColumn) Ge(value int32) MySQLRecordPredicate {
	return c.predicate(">=", int32(value), "")
}
func (c MySQLRecordComputedColumn) In(values ...int32) MySQLRecordPredicate {
	args := make([]any, len(values))
	for i, v := range values {
		args[i] = int32(v)
	}
	return c.predicate("in", args, "")
}

type MySQLRecordFlagColumn struct{ valid bool }

func (MySQLRecordFlagColumn) String() string { return "goquent: generated details omitted" }
func (MySQLRecordFlagColumn) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLRecordFlagColumn) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c MySQLRecordFlagColumn) predicate(op string, value any, ref string) MySQLRecordPredicate {
	if !c.valid {
		return MySQLRecordPredicate{}
	}
	return MySQLRecordPredicate{filter: operation.FilterSpec{Field: "flag", Op: op, Value: value, ValueRef: ref}}
}
func (c MySQLRecordFlagColumn) Asc() MySQLRecordOrder {
	if !c.valid {
		return MySQLRecordOrder{}
	}
	return MySQLRecordOrder{order: operation.OrderSpec{Field: "flag", Direction: "asc"}}
}
func (c MySQLRecordFlagColumn) Desc() MySQLRecordOrder {
	if !c.valid {
		return MySQLRecordOrder{}
	}
	return MySQLRecordOrder{order: operation.OrderSpec{Field: "flag", Direction: "desc"}}
}
func (c MySQLRecordFlagColumn) IsNull() MySQLRecordPredicate { return c.predicate("is_null", nil, "") }
func (c MySQLRecordFlagColumn) IsNotNull() MySQLRecordPredicate {
	return c.predicate("is_not_null", nil, "")
}
func (c MySQLRecordFlagColumn) Eq(value bool) MySQLRecordPredicate {
	return c.predicate("=", bool(value), "")
}
func (c MySQLRecordFlagColumn) Ne(value bool) MySQLRecordPredicate {
	return c.predicate("!=", bool(value), "")
}
func (c MySQLRecordFlagColumn) In(values ...bool) MySQLRecordPredicate {
	args := make([]any, len(values))
	for i, v := range values {
		args[i] = bool(v)
	}
	return c.predicate("in", args, "")
}

type MySQLRecordHappenedColumn struct{ valid bool }

func (MySQLRecordHappenedColumn) String() string { return "goquent: generated details omitted" }
func (MySQLRecordHappenedColumn) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLRecordHappenedColumn) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c MySQLRecordHappenedColumn) predicate(op string, value any, ref string) MySQLRecordPredicate {
	if !c.valid {
		return MySQLRecordPredicate{}
	}
	return MySQLRecordPredicate{filter: operation.FilterSpec{Field: "happened", Op: op, Value: value, ValueRef: ref}}
}
func (c MySQLRecordHappenedColumn) Asc() MySQLRecordOrder {
	if !c.valid {
		return MySQLRecordOrder{}
	}
	return MySQLRecordOrder{order: operation.OrderSpec{Field: "happened", Direction: "asc"}}
}
func (c MySQLRecordHappenedColumn) Desc() MySQLRecordOrder {
	if !c.valid {
		return MySQLRecordOrder{}
	}
	return MySQLRecordOrder{order: operation.OrderSpec{Field: "happened", Direction: "desc"}}
}
func (c MySQLRecordHappenedColumn) IsNull() MySQLRecordPredicate {
	return c.predicate("is_null", nil, "")
}
func (c MySQLRecordHappenedColumn) IsNotNull() MySQLRecordPredicate {
	return c.predicate("is_not_null", nil, "")
}
func (c MySQLRecordHappenedColumn) Eq(value string) MySQLRecordPredicate {
	return c.predicate("=", string(value), "")
}
func (c MySQLRecordHappenedColumn) Ne(value string) MySQLRecordPredicate {
	return c.predicate("!=", string(value), "")
}
func (c MySQLRecordHappenedColumn) Lt(value string) MySQLRecordPredicate {
	return c.predicate("<", string(value), "")
}
func (c MySQLRecordHappenedColumn) Le(value string) MySQLRecordPredicate {
	return c.predicate("<=", string(value), "")
}
func (c MySQLRecordHappenedColumn) Gt(value string) MySQLRecordPredicate {
	return c.predicate(">", string(value), "")
}
func (c MySQLRecordHappenedColumn) Ge(value string) MySQLRecordPredicate {
	return c.predicate(">=", string(value), "")
}
func (c MySQLRecordHappenedColumn) In(values ...string) MySQLRecordPredicate {
	args := make([]any, len(values))
	for i, v := range values {
		args[i] = string(v)
	}
	return c.predicate("in", args, "")
}

type MySQLRecordIDKey int64

func (MySQLRecordIDKey) String() string { return "goquent: generated details omitted" }
func (MySQLRecordIDKey) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLRecordIDKey) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}

type MySQLRecordIDColumn struct{ valid bool }

func (MySQLRecordIDColumn) String() string { return "goquent: generated details omitted" }
func (MySQLRecordIDColumn) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLRecordIDColumn) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c MySQLRecordIDColumn) predicate(op string, value any, ref string) MySQLRecordPredicate {
	if !c.valid {
		return MySQLRecordPredicate{}
	}
	return MySQLRecordPredicate{filter: operation.FilterSpec{Field: "id", Op: op, Value: value, ValueRef: ref}}
}
func (c MySQLRecordIDColumn) Asc() MySQLRecordOrder {
	if !c.valid {
		return MySQLRecordOrder{}
	}
	return MySQLRecordOrder{order: operation.OrderSpec{Field: "id", Direction: "asc"}}
}
func (c MySQLRecordIDColumn) Desc() MySQLRecordOrder {
	if !c.valid {
		return MySQLRecordOrder{}
	}
	return MySQLRecordOrder{order: operation.OrderSpec{Field: "id", Direction: "desc"}}
}
func (c MySQLRecordIDColumn) IsNull() MySQLRecordPredicate { return c.predicate("is_null", nil, "") }
func (c MySQLRecordIDColumn) IsNotNull() MySQLRecordPredicate {
	return c.predicate("is_not_null", nil, "")
}
func (c MySQLRecordIDColumn) Eq(value MySQLRecordIDKey) MySQLRecordPredicate {
	return c.predicate("=", int64(value), "")
}
func (c MySQLRecordIDColumn) Ne(value MySQLRecordIDKey) MySQLRecordPredicate {
	return c.predicate("!=", int64(value), "")
}
func (c MySQLRecordIDColumn) Lt(value MySQLRecordIDKey) MySQLRecordPredicate {
	return c.predicate("<", int64(value), "")
}
func (c MySQLRecordIDColumn) Le(value MySQLRecordIDKey) MySQLRecordPredicate {
	return c.predicate("<=", int64(value), "")
}
func (c MySQLRecordIDColumn) Gt(value MySQLRecordIDKey) MySQLRecordPredicate {
	return c.predicate(">", int64(value), "")
}
func (c MySQLRecordIDColumn) Ge(value MySQLRecordIDKey) MySQLRecordPredicate {
	return c.predicate(">=", int64(value), "")
}
func (c MySQLRecordIDColumn) In(values ...MySQLRecordIDKey) MySQLRecordPredicate {
	args := make([]any, len(values))
	for i, v := range values {
		args[i] = int64(v)
	}
	return c.predicate("in", args, "")
}

type MySQLRecordImmutableColumn struct{ valid bool }

func (MySQLRecordImmutableColumn) String() string { return "goquent: generated details omitted" }
func (MySQLRecordImmutableColumn) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLRecordImmutableColumn) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c MySQLRecordImmutableColumn) predicate(op string, value any, ref string) MySQLRecordPredicate {
	if !c.valid {
		return MySQLRecordPredicate{}
	}
	return MySQLRecordPredicate{filter: operation.FilterSpec{Field: "immutable", Op: op, Value: value, ValueRef: ref}}
}
func (c MySQLRecordImmutableColumn) Asc() MySQLRecordOrder {
	if !c.valid {
		return MySQLRecordOrder{}
	}
	return MySQLRecordOrder{order: operation.OrderSpec{Field: "immutable", Direction: "asc"}}
}
func (c MySQLRecordImmutableColumn) Desc() MySQLRecordOrder {
	if !c.valid {
		return MySQLRecordOrder{}
	}
	return MySQLRecordOrder{order: operation.OrderSpec{Field: "immutable", Direction: "desc"}}
}
func (c MySQLRecordImmutableColumn) IsNull() MySQLRecordPredicate {
	return c.predicate("is_null", nil, "")
}
func (c MySQLRecordImmutableColumn) IsNotNull() MySQLRecordPredicate {
	return c.predicate("is_not_null", nil, "")
}
func (c MySQLRecordImmutableColumn) Eq(value string) MySQLRecordPredicate {
	return c.predicate("=", string(value), "")
}
func (c MySQLRecordImmutableColumn) Ne(value string) MySQLRecordPredicate {
	return c.predicate("!=", string(value), "")
}
func (c MySQLRecordImmutableColumn) Lt(value string) MySQLRecordPredicate {
	return c.predicate("<", string(value), "")
}
func (c MySQLRecordImmutableColumn) Le(value string) MySQLRecordPredicate {
	return c.predicate("<=", string(value), "")
}
func (c MySQLRecordImmutableColumn) Gt(value string) MySQLRecordPredicate {
	return c.predicate(">", string(value), "")
}
func (c MySQLRecordImmutableColumn) Ge(value string) MySQLRecordPredicate {
	return c.predicate(">=", string(value), "")
}
func (c MySQLRecordImmutableColumn) Like(value string) MySQLRecordPredicate {
	return c.predicate("like", string(value), "")
}
func (c MySQLRecordImmutableColumn) In(values ...string) MySQLRecordPredicate {
	args := make([]any, len(values))
	for i, v := range values {
		args[i] = string(v)
	}
	return c.predicate("in", args, "")
}

type MySQLRecordNoteColumn struct{ valid bool }

func (MySQLRecordNoteColumn) String() string { return "goquent: generated details omitted" }
func (MySQLRecordNoteColumn) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLRecordNoteColumn) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c MySQLRecordNoteColumn) predicate(op string, value any, ref string) MySQLRecordPredicate {
	if !c.valid {
		return MySQLRecordPredicate{}
	}
	return MySQLRecordPredicate{filter: operation.FilterSpec{Field: "note", Op: op, Value: value, ValueRef: ref}}
}
func (c MySQLRecordNoteColumn) Asc() MySQLRecordOrder {
	if !c.valid {
		return MySQLRecordOrder{}
	}
	return MySQLRecordOrder{order: operation.OrderSpec{Field: "note", Direction: "asc"}}
}
func (c MySQLRecordNoteColumn) Desc() MySQLRecordOrder {
	if !c.valid {
		return MySQLRecordOrder{}
	}
	return MySQLRecordOrder{order: operation.OrderSpec{Field: "note", Direction: "desc"}}
}
func (c MySQLRecordNoteColumn) IsNull() MySQLRecordPredicate { return c.predicate("is_null", nil, "") }
func (c MySQLRecordNoteColumn) IsNotNull() MySQLRecordPredicate {
	return c.predicate("is_not_null", nil, "")
}
func (c MySQLRecordNoteColumn) Eq(value string) MySQLRecordPredicate {
	return c.predicate("=", string(value), "")
}
func (c MySQLRecordNoteColumn) Ne(value string) MySQLRecordPredicate {
	return c.predicate("!=", string(value), "")
}
func (c MySQLRecordNoteColumn) Lt(value string) MySQLRecordPredicate {
	return c.predicate("<", string(value), "")
}
func (c MySQLRecordNoteColumn) Le(value string) MySQLRecordPredicate {
	return c.predicate("<=", string(value), "")
}
func (c MySQLRecordNoteColumn) Gt(value string) MySQLRecordPredicate {
	return c.predicate(">", string(value), "")
}
func (c MySQLRecordNoteColumn) Ge(value string) MySQLRecordPredicate {
	return c.predicate(">=", string(value), "")
}
func (c MySQLRecordNoteColumn) Like(value string) MySQLRecordPredicate {
	return c.predicate("like", string(value), "")
}
func (c MySQLRecordNoteColumn) In(values ...string) MySQLRecordPredicate {
	args := make([]any, len(values))
	for i, v := range values {
		args[i] = string(v)
	}
	return c.predicate("in", args, "")
}

type MySQLRecordSegmentKey int32

func (MySQLRecordSegmentKey) String() string { return "goquent: generated details omitted" }
func (MySQLRecordSegmentKey) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLRecordSegmentKey) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}

type MySQLRecordSegmentColumn struct{ valid bool }

func (MySQLRecordSegmentColumn) String() string { return "goquent: generated details omitted" }
func (MySQLRecordSegmentColumn) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLRecordSegmentColumn) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c MySQLRecordSegmentColumn) predicate(op string, value any, ref string) MySQLRecordPredicate {
	if !c.valid {
		return MySQLRecordPredicate{}
	}
	return MySQLRecordPredicate{filter: operation.FilterSpec{Field: "segment", Op: op, Value: value, ValueRef: ref}}
}
func (c MySQLRecordSegmentColumn) Asc() MySQLRecordOrder {
	if !c.valid {
		return MySQLRecordOrder{}
	}
	return MySQLRecordOrder{order: operation.OrderSpec{Field: "segment", Direction: "asc"}}
}
func (c MySQLRecordSegmentColumn) Desc() MySQLRecordOrder {
	if !c.valid {
		return MySQLRecordOrder{}
	}
	return MySQLRecordOrder{order: operation.OrderSpec{Field: "segment", Direction: "desc"}}
}
func (c MySQLRecordSegmentColumn) IsNull() MySQLRecordPredicate {
	return c.predicate("is_null", nil, "")
}
func (c MySQLRecordSegmentColumn) IsNotNull() MySQLRecordPredicate {
	return c.predicate("is_not_null", nil, "")
}
func (c MySQLRecordSegmentColumn) Eq(value MySQLRecordSegmentKey) MySQLRecordPredicate {
	return c.predicate("=", int32(value), "")
}
func (c MySQLRecordSegmentColumn) Ne(value MySQLRecordSegmentKey) MySQLRecordPredicate {
	return c.predicate("!=", int32(value), "")
}
func (c MySQLRecordSegmentColumn) Lt(value MySQLRecordSegmentKey) MySQLRecordPredicate {
	return c.predicate("<", int32(value), "")
}
func (c MySQLRecordSegmentColumn) Le(value MySQLRecordSegmentKey) MySQLRecordPredicate {
	return c.predicate("<=", int32(value), "")
}
func (c MySQLRecordSegmentColumn) Gt(value MySQLRecordSegmentKey) MySQLRecordPredicate {
	return c.predicate(">", int32(value), "")
}
func (c MySQLRecordSegmentColumn) Ge(value MySQLRecordSegmentKey) MySQLRecordPredicate {
	return c.predicate(">=", int32(value), "")
}
func (c MySQLRecordSegmentColumn) In(values ...MySQLRecordSegmentKey) MySQLRecordPredicate {
	args := make([]any, len(values))
	for i, v := range values {
		args[i] = int32(v)
	}
	return c.predicate("in", args, "")
}

type MySQLRecordStampColumn struct{ valid bool }

func (MySQLRecordStampColumn) String() string { return "goquent: generated details omitted" }
func (MySQLRecordStampColumn) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLRecordStampColumn) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c MySQLRecordStampColumn) predicate(op string, value any, ref string) MySQLRecordPredicate {
	if !c.valid {
		return MySQLRecordPredicate{}
	}
	return MySQLRecordPredicate{filter: operation.FilterSpec{Field: "stamp", Op: op, Value: value, ValueRef: ref}}
}
func (c MySQLRecordStampColumn) Asc() MySQLRecordOrder {
	if !c.valid {
		return MySQLRecordOrder{}
	}
	return MySQLRecordOrder{order: operation.OrderSpec{Field: "stamp", Direction: "asc"}}
}
func (c MySQLRecordStampColumn) Desc() MySQLRecordOrder {
	if !c.valid {
		return MySQLRecordOrder{}
	}
	return MySQLRecordOrder{order: operation.OrderSpec{Field: "stamp", Direction: "desc"}}
}
func (c MySQLRecordStampColumn) IsNull() MySQLRecordPredicate { return c.predicate("is_null", nil, "") }
func (c MySQLRecordStampColumn) IsNotNull() MySQLRecordPredicate {
	return c.predicate("is_not_null", nil, "")
}
func (c MySQLRecordStampColumn) Eq(value string) MySQLRecordPredicate {
	return c.predicate("=", string(value), "")
}
func (c MySQLRecordStampColumn) Ne(value string) MySQLRecordPredicate {
	return c.predicate("!=", string(value), "")
}
func (c MySQLRecordStampColumn) Lt(value string) MySQLRecordPredicate {
	return c.predicate("<", string(value), "")
}
func (c MySQLRecordStampColumn) Le(value string) MySQLRecordPredicate {
	return c.predicate("<=", string(value), "")
}
func (c MySQLRecordStampColumn) Gt(value string) MySQLRecordPredicate {
	return c.predicate(">", string(value), "")
}
func (c MySQLRecordStampColumn) Ge(value string) MySQLRecordPredicate {
	return c.predicate(">=", string(value), "")
}
func (c MySQLRecordStampColumn) In(values ...string) MySQLRecordPredicate {
	args := make([]any, len(values))
	for i, v := range values {
		args[i] = string(v)
	}
	return c.predicate("in", args, "")
}

type MySQLRecordStatusValue string

func (MySQLRecordStatusValue) String() string { return "goquent: generated details omitted" }
func (MySQLRecordStatusValue) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLRecordStatusValue) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}

const MySQLRecordStatusValueChoice1 MySQLRecordStatusValue = "ready"
const MySQLRecordStatusValueChoice2 MySQLRecordStatusValue = "closed"
const MySQLRecordStatusValueChoice3 MySQLRecordStatusValue = "a-b"
const MySQLRecordStatusValueChoice4 MySQLRecordStatusValue = "a_b"
const MySQLRecordStatusValueChoice5 MySQLRecordStatusValue = "type"

type MySQLRecordStatusColumn struct{ valid bool }

func (MySQLRecordStatusColumn) String() string { return "goquent: generated details omitted" }
func (MySQLRecordStatusColumn) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLRecordStatusColumn) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c MySQLRecordStatusColumn) predicate(op string, value any, ref string) MySQLRecordPredicate {
	if !c.valid {
		return MySQLRecordPredicate{}
	}
	return MySQLRecordPredicate{filter: operation.FilterSpec{Field: "status", Op: op, Value: value, ValueRef: ref}}
}
func (c MySQLRecordStatusColumn) Asc() MySQLRecordOrder {
	if !c.valid {
		return MySQLRecordOrder{}
	}
	return MySQLRecordOrder{order: operation.OrderSpec{Field: "status", Direction: "asc"}}
}
func (c MySQLRecordStatusColumn) Desc() MySQLRecordOrder {
	if !c.valid {
		return MySQLRecordOrder{}
	}
	return MySQLRecordOrder{order: operation.OrderSpec{Field: "status", Direction: "desc"}}
}
func (c MySQLRecordStatusColumn) IsNull() MySQLRecordPredicate {
	return c.predicate("is_null", nil, "")
}
func (c MySQLRecordStatusColumn) IsNotNull() MySQLRecordPredicate {
	return c.predicate("is_not_null", nil, "")
}
func (c MySQLRecordStatusColumn) Eq(value MySQLRecordStatusValue) MySQLRecordPredicate {
	return c.predicate("=", string(value), "")
}
func (c MySQLRecordStatusColumn) Ne(value MySQLRecordStatusValue) MySQLRecordPredicate {
	return c.predicate("!=", string(value), "")
}
func (c MySQLRecordStatusColumn) Lt(value MySQLRecordStatusValue) MySQLRecordPredicate {
	return c.predicate("<", string(value), "")
}
func (c MySQLRecordStatusColumn) Le(value MySQLRecordStatusValue) MySQLRecordPredicate {
	return c.predicate("<=", string(value), "")
}
func (c MySQLRecordStatusColumn) Gt(value MySQLRecordStatusValue) MySQLRecordPredicate {
	return c.predicate(">", string(value), "")
}
func (c MySQLRecordStatusColumn) Ge(value MySQLRecordStatusValue) MySQLRecordPredicate {
	return c.predicate(">=", string(value), "")
}
func (c MySQLRecordStatusColumn) Like(value MySQLRecordStatusValue) MySQLRecordPredicate {
	return c.predicate("like", string(value), "")
}
func (c MySQLRecordStatusColumn) In(values ...MySQLRecordStatusValue) MySQLRecordPredicate {
	args := make([]any, len(values))
	for i, v := range values {
		args[i] = string(v)
	}
	return c.predicate("in", args, "")
}

type MySQLRecordSummaryRow struct {
	ID       int64               `db:"id"`
	Segment  int32               `db:"segment"`
	Status   string              `db:"status"`
	Active   bool                `db:"active"`
	Flag     sql.NullBool        `db:"flag"`
	Note     sql.Null[string]    `db:"note"`
	Balance  string              `db:"balance"`
	Happened time.Time           `db:"happened"`
	Clock    MySQLRecordTimeText `db:"clock"`
	Stamp    time.Time           `db:"stamp"`
}

func (MySQLRecordSummaryRow) String() string { return "goquent: generated details omitted" }
func (MySQLRecordSummaryRow) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLRecordSummaryRow) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (r *MySQLRecordRepository) PlanSummary(ctx context.Context, input MySQLRecordRead) (*orm.QueryPlan, operation.DiagnosticView, error) {
	return r.db.CompileOperationWithDiagnostics(ctx, input.spec([]string{"id", "segment", "status", "active", "flag", "note", "balance", "happened", "clock", "stamp"}), operation.Options{Manifest: mySQLRecordSnapshot()})
}
func (r *MySQLRecordRepository) SelectSummary(ctx context.Context, input MySQLRecordRead) ([]MySQLRecordSummaryRow, error) {
	return orm.SelectOperationBy[MySQLRecordSummaryRow](ctx, r.db, input.spec([]string{"id", "segment", "status", "active", "flag", "note", "balance", "happened", "clock", "stamp"}), operation.Options{Manifest: mySQLRecordSnapshot()})
}

type MySQLRecordIdentityRow struct {
	Segment int32 `db:"segment"`
	ID      int64 `db:"id"`
}

func (MySQLRecordIdentityRow) String() string { return "goquent: generated details omitted" }
func (MySQLRecordIdentityRow) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLRecordIdentityRow) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (r *MySQLRecordRepository) PlanIdentity(ctx context.Context, input MySQLRecordRead) (*orm.QueryPlan, operation.DiagnosticView, error) {
	return r.db.CompileOperationWithDiagnostics(ctx, input.spec([]string{"segment", "id"}), operation.Options{Manifest: mySQLRecordSnapshot()})
}
func (r *MySQLRecordRepository) SelectIdentity(ctx context.Context, input MySQLRecordRead) ([]MySQLRecordIdentityRow, error) {
	return orm.SelectOperationBy[MySQLRecordIdentityRow](ctx, r.db, input.spec([]string{"segment", "id"}), operation.Options{Manifest: mySQLRecordSnapshot()})
}

type MySQLRecordKey struct {
	ID      MySQLRecordIDKey
	Segment MySQLRecordSegmentKey
}

func (MySQLRecordKey) String() string { return "goquent: generated details omitted" }
func (MySQLRecordKey) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (MySQLRecordKey) MarshalJSON() ([]byte, error) { return []byte("{\"details_omitted\":true}"), nil }
func mySQLRecordKeyInput(key MySQLRecordKey, input MySQLRecordRead) MySQLRecordRead {
	input.Filters = append([]MySQLRecordPredicate(nil), input.Filters...)
	cols := MySQLRecordColumns()
	input.Filters = append(input.Filters, cols.ID.Eq(key.ID))
	input.Filters = append(input.Filters, cols.Segment.Eq(key.Segment))
	return input
}
func (r *MySQLRecordRepository) PlanFindByKey(ctx context.Context, key MySQLRecordKey, input MySQLRecordRead) (*orm.QueryPlan, operation.DiagnosticView, error) {
	input = mySQLRecordKeyInput(key, input)
	return r.db.CompileOperationWithDiagnostics(ctx, input.spec([]string{"active", "balance", "clock", "computed", "flag", "happened", "id", "immutable", "note", "segment", "stamp", "status"}), operation.Options{Manifest: mySQLRecordSnapshot()})
}
func (r *MySQLRecordRepository) FindByKey(ctx context.Context, key MySQLRecordKey, input MySQLRecordRead) (MySQLRecordRow, error) {
	input = mySQLRecordKeyInput(key, input)
	rows, err := orm.SelectOperationBy[MySQLRecordRow](ctx, r.db, input.spec([]string{"active", "balance", "clock", "computed", "flag", "happened", "id", "immutable", "note", "segment", "stamp", "status"}), operation.Options{Manifest: mySQLRecordSnapshot()})
	if err != nil {
		return MySQLRecordRow{}, err
	}
	if len(rows) == 0 {
		return MySQLRecordRow{}, orm.ErrNotFound
	}
	return rows[0], nil
}
