// Code generated by goquent typed-repository-v1; DO NOT EDIT.
// Snapshot kind: manifest; supplied declarations only, not live identity or authorization.
// Schema fingerprint: ""
// Policy fingerprint: ""
package typedfixture

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/recoweft/goquent/orm"
	"github.com/recoweft/goquent/orm/manifest"
	"github.com/recoweft/goquent/orm/operation"
)

type TenantRecordRow struct {
	Active   bool  `db:"active"`
	ID       int64 `db:"id,pk"`
	TenantID int64 `db:"tenant_id,pk"`
}

func (TenantRecordRow) TableName() string { return "gq08_tenants" }

type TenantRecordRepository struct {
	db *orm.DB
}

func NewTenantRecordRepository(db *orm.DB) *TenantRecordRepository {
	return &TenantRecordRepository{db: db}
}

func (TenantRecordRow) String() string { return "goquent: generated details omitted" }
func (TenantRecordRow) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (TenantRecordRow) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (TenantRecordRepository) String() string { return "goquent: generated details omitted" }
func (TenantRecordRepository) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (TenantRecordRepository) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}

type TenantRecordPredicate struct{ filter operation.FilterSpec }
type TenantRecordOrder struct{ order operation.OrderSpec }

// TenantRecordRead carries typed filters and ordering. Runtime validation still applies.
type TenantRecordRead struct {
	Filters      []TenantRecordPredicate
	OrderBy      []TenantRecordOrder
	Limit        *int64
	AccessReason string
}

func (TenantRecordPredicate) String() string { return "goquent: generated details omitted" }
func (TenantRecordPredicate) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (TenantRecordPredicate) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (TenantRecordOrder) String() string { return "goquent: generated details omitted" }
func (TenantRecordOrder) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (TenantRecordOrder) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (TenantRecordRead) String() string { return "goquent: generated details omitted" }
func (TenantRecordRead) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (TenantRecordRead) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func tenantRecordSnapshot() *manifest.Manifest {
	var m manifest.Manifest
	_ = json.Unmarshal([]byte("{\"version\":\"1\",\"generated_at\":\"0001-01-01T00:00:00Z\",\"generator_version\":\"\",\"dialect\":\"postgres\",\"tables\":[{\"name\":\"gq08_tenants\",\"columns\":[{\"name\":\"id\",\"type\":\"bigint\",\"type_source\":\"sql\",\"primary\":true,\"nullable\":false},{\"name\":\"tenant_id\",\"type\":\"bigint\",\"type_source\":\"sql\",\"primary\":true,\"nullable\":false,\"tenant_scope\":true,\"required_filter\":true},{\"name\":\"active\",\"type\":\"boolean\",\"type_source\":\"sql\",\"nullable\":false}]}]}"), &m)
	return &m
}
func (in TenantRecordRead) spec(columns []string) operation.OperationSpec {
	s := operation.OperationSpec{Version: 1, Operation: "select", Model: "gq08_tenants", Select: columns, AccessReason: in.AccessReason}
	if in.Limit != nil {
		n := *in.Limit
		s.Limit = &n
	}
	for _, f := range in.Filters {
		s.Filters = append(s.Filters, f.filter)
	}
	for _, o := range in.OrderBy {
		s.OrderBy = append(s.OrderBy, o.order)
	}
	return s
}

type TenantRecordColumnSet struct {
	Active   TenantRecordActiveColumn
	ID       TenantRecordIDColumn
	TenantID TenantRecordTenantIDColumn
}

func (TenantRecordColumnSet) String() string { return "goquent: generated details omitted" }
func (TenantRecordColumnSet) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (TenantRecordColumnSet) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func TenantRecordColumns() TenantRecordColumnSet {
	return TenantRecordColumnSet{Active: TenantRecordActiveColumn{valid: true}, ID: TenantRecordIDColumn{valid: true}, TenantID: TenantRecordTenantIDColumn{valid: true}}
}

type TenantRecordActiveColumn struct{ valid bool }

func (TenantRecordActiveColumn) String() string { return "goquent: generated details omitted" }
func (TenantRecordActiveColumn) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (TenantRecordActiveColumn) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c TenantRecordActiveColumn) predicate(op string, value any, ref string) TenantRecordPredicate {
	if !c.valid {
		return TenantRecordPredicate{}
	}
	return TenantRecordPredicate{filter: operation.FilterSpec{Field: "active", Op: op, Value: value, ValueRef: ref}}
}
func (c TenantRecordActiveColumn) Asc() TenantRecordOrder {
	if !c.valid {
		return TenantRecordOrder{}
	}
	return TenantRecordOrder{order: operation.OrderSpec{Field: "active", Direction: "asc"}}
}
func (c TenantRecordActiveColumn) Desc() TenantRecordOrder {
	if !c.valid {
		return TenantRecordOrder{}
	}
	return TenantRecordOrder{order: operation.OrderSpec{Field: "active", Direction: "desc"}}
}
func (c TenantRecordActiveColumn) IsNull() TenantRecordPredicate {
	return c.predicate("is_null", nil, "")
}
func (c TenantRecordActiveColumn) IsNotNull() TenantRecordPredicate {
	return c.predicate("is_not_null", nil, "")
}
func (c TenantRecordActiveColumn) Eq(value bool) TenantRecordPredicate {
	return c.predicate("=", bool(value), "")
}
func (c TenantRecordActiveColumn) Ne(value bool) TenantRecordPredicate {
	return c.predicate("!=", bool(value), "")
}
func (c TenantRecordActiveColumn) In(values ...bool) TenantRecordPredicate {
	args := make([]any, len(values))
	for i, v := range values {
		args[i] = bool(v)
	}
	return c.predicate("in", args, "")
}

type TenantRecordIDKey int64

func (TenantRecordIDKey) String() string { return "goquent: generated details omitted" }
func (TenantRecordIDKey) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (TenantRecordIDKey) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}

type TenantRecordIDColumn struct{ valid bool }

func (TenantRecordIDColumn) String() string { return "goquent: generated details omitted" }
func (TenantRecordIDColumn) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (TenantRecordIDColumn) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c TenantRecordIDColumn) predicate(op string, value any, ref string) TenantRecordPredicate {
	if !c.valid {
		return TenantRecordPredicate{}
	}
	return TenantRecordPredicate{filter: operation.FilterSpec{Field: "id", Op: op, Value: value, ValueRef: ref}}
}
func (c TenantRecordIDColumn) Asc() TenantRecordOrder {
	if !c.valid {
		return TenantRecordOrder{}
	}
	return TenantRecordOrder{order: operation.OrderSpec{Field: "id", Direction: "asc"}}
}
func (c TenantRecordIDColumn) Desc() TenantRecordOrder {
	if !c.valid {
		return TenantRecordOrder{}
	}
	return TenantRecordOrder{order: operation.OrderSpec{Field: "id", Direction: "desc"}}
}
func (c TenantRecordIDColumn) IsNull() TenantRecordPredicate { return c.predicate("is_null", nil, "") }
func (c TenantRecordIDColumn) IsNotNull() TenantRecordPredicate {
	return c.predicate("is_not_null", nil, "")
}
func (c TenantRecordIDColumn) Eq(value TenantRecordIDKey) TenantRecordPredicate {
	return c.predicate("=", int64(value), "")
}
func (c TenantRecordIDColumn) Ne(value TenantRecordIDKey) TenantRecordPredicate {
	return c.predicate("!=", int64(value), "")
}
func (c TenantRecordIDColumn) Lt(value TenantRecordIDKey) TenantRecordPredicate {
	return c.predicate("<", int64(value), "")
}
func (c TenantRecordIDColumn) Le(value TenantRecordIDKey) TenantRecordPredicate {
	return c.predicate("<=", int64(value), "")
}
func (c TenantRecordIDColumn) Gt(value TenantRecordIDKey) TenantRecordPredicate {
	return c.predicate(">", int64(value), "")
}
func (c TenantRecordIDColumn) Ge(value TenantRecordIDKey) TenantRecordPredicate {
	return c.predicate(">=", int64(value), "")
}
func (c TenantRecordIDColumn) In(values ...TenantRecordIDKey) TenantRecordPredicate {
	args := make([]any, len(values))
	for i, v := range values {
		args[i] = int64(v)
	}
	return c.predicate("in", args, "")
}

type TenantRecordTenantIDKey struct{ present bool }

func TenantRecordCurrentTenantKey() TenantRecordTenantIDKey {
	return TenantRecordTenantIDKey{present: true}
}
func (TenantRecordTenantIDKey) String() string { return "goquent: generated details omitted" }
func (TenantRecordTenantIDKey) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (TenantRecordTenantIDKey) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}

type TenantRecordTenantIDColumn struct{ valid bool }

func (TenantRecordTenantIDColumn) String() string { return "goquent: generated details omitted" }
func (TenantRecordTenantIDColumn) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (TenantRecordTenantIDColumn) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c TenantRecordTenantIDColumn) predicate(op string, value any, ref string) TenantRecordPredicate {
	if !c.valid {
		return TenantRecordPredicate{}
	}
	return TenantRecordPredicate{filter: operation.FilterSpec{Field: "tenant_id", Op: op, Value: value, ValueRef: ref}}
}
func (c TenantRecordTenantIDColumn) Asc() TenantRecordOrder {
	if !c.valid {
		return TenantRecordOrder{}
	}
	return TenantRecordOrder{order: operation.OrderSpec{Field: "tenant_id", Direction: "asc"}}
}
func (c TenantRecordTenantIDColumn) Desc() TenantRecordOrder {
	if !c.valid {
		return TenantRecordOrder{}
	}
	return TenantRecordOrder{order: operation.OrderSpec{Field: "tenant_id", Direction: "desc"}}
}
func (c TenantRecordTenantIDColumn) CurrentTenant() TenantRecordPredicate {
	return c.predicate("=", nil, "current_tenant")
}

type TenantRecordIdentityRow struct {
	ID       int64 `db:"id"`
	TenantID int64 `db:"tenant_id"`
	Active   bool  `db:"active"`
}

func (TenantRecordIdentityRow) String() string { return "goquent: generated details omitted" }
func (TenantRecordIdentityRow) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (TenantRecordIdentityRow) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (r *TenantRecordRepository) PlanIdentity(ctx context.Context, input TenantRecordRead) (*orm.QueryPlan, operation.DiagnosticView, error) {
	return r.db.CompileOperationWithDiagnostics(ctx, input.spec([]string{"id", "tenant_id", "active"}), operation.Options{Manifest: tenantRecordSnapshot()})
}
func (r *TenantRecordRepository) SelectIdentity(ctx context.Context, input TenantRecordRead) ([]TenantRecordIdentityRow, error) {
	return orm.SelectOperationBy[TenantRecordIdentityRow](ctx, r.db, input.spec([]string{"id", "tenant_id", "active"}), operation.Options{Manifest: tenantRecordSnapshot()})
}

type TenantRecordKey struct {
	ID       TenantRecordIDKey
	TenantID TenantRecordTenantIDKey
}

func (TenantRecordKey) String() string { return "goquent: generated details omitted" }
func (TenantRecordKey) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (TenantRecordKey) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func tenantRecordKeyInput(key TenantRecordKey, input TenantRecordRead) TenantRecordRead {
	input.Filters = append([]TenantRecordPredicate(nil), input.Filters...)
	cols := TenantRecordColumns()
	input.Filters = append(input.Filters, cols.ID.Eq(key.ID))
	if key.TenantID.present {
		input.Filters = append(input.Filters, cols.TenantID.CurrentTenant())
	} else {
		input.Filters = append(input.Filters, TenantRecordPredicate{})
	}
	return input
}
func (r *TenantRecordRepository) PlanFindByKey(ctx context.Context, key TenantRecordKey, input TenantRecordRead) (*orm.QueryPlan, operation.DiagnosticView, error) {
	input = tenantRecordKeyInput(key, input)
	return r.db.CompileOperationWithDiagnostics(ctx, input.spec([]string{"active", "id", "tenant_id"}), operation.Options{Manifest: tenantRecordSnapshot()})
}
func (r *TenantRecordRepository) FindByKey(ctx context.Context, key TenantRecordKey, input TenantRecordRead) (TenantRecordRow, error) {
	input = tenantRecordKeyInput(key, input)
	rows, err := orm.SelectOperationBy[TenantRecordRow](ctx, r.db, input.spec([]string{"active", "id", "tenant_id"}), operation.Options{Manifest: tenantRecordSnapshot()})
	if err != nil {
		return TenantRecordRow{}, err
	}
	if len(rows) == 0 {
		return TenantRecordRow{}, orm.ErrNotFound
	}
	return rows[0], nil
}
