// Code generated by goquent typed-repository-v1; DO NOT EDIT.
// Snapshot kind: manifest; supplied declarations only, not live identity or authorization.
// Schema fingerprint: "fictional-schema"
// Policy fingerprint: "fictional-policy"
package typedfixture

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"time"

	"github.com/recoweft/goquent/orm"
	"github.com/recoweft/goquent/orm/manifest"
	"github.com/recoweft/goquent/orm/operation"
)

type PostgresRecordRow struct {
	Active    bool                   `db:"active"`
	Balance   string                 `db:"balance"`
	Clock     PostgresRecordTimeText `db:"clock"`
	Computed  int32                  `db:"computed,readonly"`
	Flag      sql.NullBool           `db:"flag"`
	Happened  time.Time              `db:"happened"`
	Hidden    string                 `db:"hidden"`
	ID        int64                  `db:"id,pk"`
	Immutable string                 `db:"immutable,readonly"`
	Note      sql.Null[string]       `db:"note"`
	Segment   int32                  `db:"segment,pk"`
	Stamp     time.Time              `db:"stamp"`
	Status    string                 `db:"status"`
}

func (PostgresRecordRow) TableName() string { return "gq08_records" }

type PostgresRecordRepository struct {
	db *orm.DB
}

func NewPostgresRecordRepository(db *orm.DB) *PostgresRecordRepository {
	return &PostgresRecordRepository{db: db}
}

// PostgresRecordTimeText scans the built-in drivers' clock results without a driver argument adapter.
type PostgresRecordTimeText string

func (v *PostgresRecordTimeText) Scan(source any) error {
	switch x := source.(type) {
	case string:
		*v = PostgresRecordTimeText(x)
	case []byte:
		*v = PostgresRecordTimeText(string(x))
	case time.Time:
		if x.Year() != 0 || x.Month() != time.January || x.Day() != 1 {
			return fmt.Errorf("goquent: clock result is unsupported")
		}
		*v = PostgresRecordTimeText(x.Format("15:04:05.999999999"))
	default:
		return fmt.Errorf("goquent: clock result is unsupported")
	}
	return nil
}
func (PostgresRecordTimeText) String() string { return "goquent: generated details omitted" }
func (PostgresRecordTimeText) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (PostgresRecordTimeText) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (PostgresRecordRow) String() string { return "goquent: generated details omitted" }
func (PostgresRecordRow) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (PostgresRecordRow) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (PostgresRecordRepository) String() string { return "goquent: generated details omitted" }
func (PostgresRecordRepository) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (PostgresRecordRepository) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}

type PostgresRecordPredicate struct{ filter operation.FilterSpec }
type PostgresRecordOrder struct{ order operation.OrderSpec }

// PostgresRecordRead carries typed filters and ordering. Runtime validation still applies.
type PostgresRecordRead struct {
	Filters      []PostgresRecordPredicate
	OrderBy      []PostgresRecordOrder
	Limit        *int64
	AccessReason string
}

func (PostgresRecordPredicate) String() string { return "goquent: generated details omitted" }
func (PostgresRecordPredicate) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (PostgresRecordPredicate) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (PostgresRecordOrder) String() string { return "goquent: generated details omitted" }
func (PostgresRecordOrder) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (PostgresRecordOrder) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (PostgresRecordRead) String() string { return "goquent: generated details omitted" }
func (PostgresRecordRead) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (PostgresRecordRead) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func postgresRecordSnapshot() *manifest.Manifest {
	var m manifest.Manifest
	_ = json.Unmarshal([]byte("{\"version\":\"1\",\"generated_at\":\"1970-01-01T00:00:01Z\",\"generator_version\":\"fixture\",\"dialect\":\"postgres\",\"schema_fingerprint\":\"fictional-schema\",\"policy_fingerprint\":\"fictional-policy\",\"tables\":[{\"name\":\"gq08_records\",\"columns\":[{\"name\":\"id\",\"type\":\"bigint\",\"type_source\":\"sql\",\"primary\":true,\"nullable\":false},{\"name\":\"segment\",\"type\":\"integer\",\"type_source\":\"sql\",\"primary\":true,\"nullable\":false},{\"name\":\"status\",\"type\":\"varchar(12)\",\"type_source\":\"sql\",\"nullable\":false,\"enum_values\":[\"ready\",\"closed\",\"a-b\",\"a_b\",\"type\"]},{\"name\":\"active\",\"type\":\"boolean\",\"type_source\":\"sql\",\"nullable\":false},{\"name\":\"flag\",\"type\":\"boolean\",\"type_source\":\"sql\",\"nullable\":true},{\"name\":\"note\",\"type\":\"text\",\"type_source\":\"sql\",\"nullable\":true},{\"name\":\"balance\",\"type\":\"decimal(30,4)\",\"type_source\":\"sql\",\"nullable\":false},{\"name\":\"happened\",\"type\":\"date\",\"type_source\":\"sql\",\"nullable\":false},{\"name\":\"clock\",\"type\":\"time(6)\",\"type_source\":\"sql\",\"nullable\":false},{\"name\":\"stamp\",\"type\":\"timestamp(6) without time zone\",\"type_source\":\"sql\",\"nullable\":false},{\"name\":\"immutable\",\"type\":\"text\",\"type_source\":\"sql\",\"nullable\":false,\"readonly\":true},{\"name\":\"computed\",\"type\":\"integer\",\"type_source\":\"sql\",\"nullable\":false,\"generated\":true},{\"name\":\"hidden\",\"type\":\"text\",\"type_source\":\"sql\",\"nullable\":false,\"forbidden\":true}]}]}"), &m)
	return &m
}
func (in PostgresRecordRead) spec(columns []string) operation.OperationSpec {
	s := operation.OperationSpec{Version: 1, Operation: "select", Model: "gq08_records", Select: columns, AccessReason: in.AccessReason}
	if in.Limit != nil {
		n := *in.Limit
		s.Limit = &n
	}
	for _, f := range in.Filters {
		s.Filters = append(s.Filters, f.filter)
	}
	for _, o := range in.OrderBy {
		s.OrderBy = append(s.OrderBy, o.order)
	}
	return s
}

type PostgresRecordColumnSet struct {
	Active    PostgresRecordActiveColumn
	Balance   PostgresRecordBalanceColumn
	Clock     PostgresRecordClockColumn
	Computed  PostgresRecordComputedColumn
	Flag      PostgresRecordFlagColumn
	Happened  PostgresRecordHappenedColumn
	ID        PostgresRecordIDColumn
	Immutable PostgresRecordImmutableColumn
	Note      PostgresRecordNoteColumn
	Segment   PostgresRecordSegmentColumn
	Stamp     PostgresRecordStampColumn
	Status    PostgresRecordStatusColumn
}

func (PostgresRecordColumnSet) String() string { return "goquent: generated details omitted" }
func (PostgresRecordColumnSet) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (PostgresRecordColumnSet) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func PostgresRecordColumns() PostgresRecordColumnSet {
	return PostgresRecordColumnSet{Active: PostgresRecordActiveColumn{valid: true}, Balance: PostgresRecordBalanceColumn{valid: true}, Clock: PostgresRecordClockColumn{valid: true}, Computed: PostgresRecordComputedColumn{valid: true}, Flag: PostgresRecordFlagColumn{valid: true}, Happened: PostgresRecordHappenedColumn{valid: true}, ID: PostgresRecordIDColumn{valid: true}, Immutable: PostgresRecordImmutableColumn{valid: true}, Note: PostgresRecordNoteColumn{valid: true}, Segment: PostgresRecordSegmentColumn{valid: true}, Stamp: PostgresRecordStampColumn{valid: true}, Status: PostgresRecordStatusColumn{valid: true}}
}

type PostgresRecordActiveColumn struct{ valid bool }

func (PostgresRecordActiveColumn) String() string { return "goquent: generated details omitted" }
func (PostgresRecordActiveColumn) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (PostgresRecordActiveColumn) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c PostgresRecordActiveColumn) predicate(op string, value any, ref string) PostgresRecordPredicate {
	if !c.valid {
		return PostgresRecordPredicate{}
	}
	return PostgresRecordPredicate{filter: operation.FilterSpec{Field: "active", Op: op, Value: value, ValueRef: ref}}
}
func (c PostgresRecordActiveColumn) Asc() PostgresRecordOrder {
	if !c.valid {
		return PostgresRecordOrder{}
	}
	return PostgresRecordOrder{order: operation.OrderSpec{Field: "active", Direction: "asc"}}
}
func (c PostgresRecordActiveColumn) Desc() PostgresRecordOrder {
	if !c.valid {
		return PostgresRecordOrder{}
	}
	return PostgresRecordOrder{order: operation.OrderSpec{Field: "active", Direction: "desc"}}
}
func (c PostgresRecordActiveColumn) IsNull() PostgresRecordPredicate {
	return c.predicate("is_null", nil, "")
}
func (c PostgresRecordActiveColumn) IsNotNull() PostgresRecordPredicate {
	return c.predicate("is_not_null", nil, "")
}
func (c PostgresRecordActiveColumn) Eq(value bool) PostgresRecordPredicate {
	return c.predicate("=", bool(value), "")
}
func (c PostgresRecordActiveColumn) Ne(value bool) PostgresRecordPredicate {
	return c.predicate("!=", bool(value), "")
}
func (c PostgresRecordActiveColumn) In(values ...bool) PostgresRecordPredicate {
	args := make([]any, len(values))
	for i, v := range values {
		args[i] = bool(v)
	}
	return c.predicate("in", args, "")
}

type PostgresRecordBalanceColumn struct{ valid bool }

func (PostgresRecordBalanceColumn) String() string { return "goquent: generated details omitted" }
func (PostgresRecordBalanceColumn) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (PostgresRecordBalanceColumn) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c PostgresRecordBalanceColumn) predicate(op string, value any, ref string) PostgresRecordPredicate {
	if !c.valid {
		return PostgresRecordPredicate{}
	}
	return PostgresRecordPredicate{filter: operation.FilterSpec{Field: "balance", Op: op, Value: value, ValueRef: ref}}
}
func (c PostgresRecordBalanceColumn) Asc() PostgresRecordOrder {
	if !c.valid {
		return PostgresRecordOrder{}
	}
	return PostgresRecordOrder{order: operation.OrderSpec{Field: "balance", Direction: "asc"}}
}
func (c PostgresRecordBalanceColumn) Desc() PostgresRecordOrder {
	if !c.valid {
		return PostgresRecordOrder{}
	}
	return PostgresRecordOrder{order: operation.OrderSpec{Field: "balance", Direction: "desc"}}
}
func (c PostgresRecordBalanceColumn) IsNull() PostgresRecordPredicate {
	return c.predicate("is_null", nil, "")
}
func (c PostgresRecordBalanceColumn) IsNotNull() PostgresRecordPredicate {
	return c.predicate("is_not_null", nil, "")
}
func (c PostgresRecordBalanceColumn) Eq(value json.Number) PostgresRecordPredicate {
	return c.predicate("=", json.Number(value), "")
}
func (c PostgresRecordBalanceColumn) Ne(value json.Number) PostgresRecordPredicate {
	return c.predicate("!=", json.Number(value), "")
}
func (c PostgresRecordBalanceColumn) Lt(value json.Number) PostgresRecordPredicate {
	return c.predicate("<", json.Number(value), "")
}
func (c PostgresRecordBalanceColumn) Le(value json.Number) PostgresRecordPredicate {
	return c.predicate("<=", json.Number(value), "")
}
func (c PostgresRecordBalanceColumn) Gt(value json.Number) PostgresRecordPredicate {
	return c.predicate(">", json.Number(value), "")
}
func (c PostgresRecordBalanceColumn) Ge(value json.Number) PostgresRecordPredicate {
	return c.predicate(">=", json.Number(value), "")
}
func (c PostgresRecordBalanceColumn) In(values ...json.Number) PostgresRecordPredicate {
	args := make([]any, len(values))
	for i, v := range values {
		args[i] = json.Number(v)
	}
	return c.predicate("in", args, "")
}

type PostgresRecordClockColumn struct{ valid bool }

func (PostgresRecordClockColumn) String() string { return "goquent: generated details omitted" }
func (PostgresRecordClockColumn) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (PostgresRecordClockColumn) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c PostgresRecordClockColumn) predicate(op string, value any, ref string) PostgresRecordPredicate {
	if !c.valid {
		return PostgresRecordPredicate{}
	}
	return PostgresRecordPredicate{filter: operation.FilterSpec{Field: "clock", Op: op, Value: value, ValueRef: ref}}
}
func (c PostgresRecordClockColumn) Asc() PostgresRecordOrder {
	if !c.valid {
		return PostgresRecordOrder{}
	}
	return PostgresRecordOrder{order: operation.OrderSpec{Field: "clock", Direction: "asc"}}
}
func (c PostgresRecordClockColumn) Desc() PostgresRecordOrder {
	if !c.valid {
		return PostgresRecordOrder{}
	}
	return PostgresRecordOrder{order: operation.OrderSpec{Field: "clock", Direction: "desc"}}
}
func (c PostgresRecordClockColumn) IsNull() PostgresRecordPredicate {
	return c.predicate("is_null", nil, "")
}
func (c PostgresRecordClockColumn) IsNotNull() PostgresRecordPredicate {
	return c.predicate("is_not_null", nil, "")
}
func (c PostgresRecordClockColumn) Eq(value string) PostgresRecordPredicate {
	return c.predicate("=", string(value), "")
}
func (c PostgresRecordClockColumn) Ne(value string) PostgresRecordPredicate {
	return c.predicate("!=", string(value), "")
}
func (c PostgresRecordClockColumn) Lt(value string) PostgresRecordPredicate {
	return c.predicate("<", string(value), "")
}
func (c PostgresRecordClockColumn) Le(value string) PostgresRecordPredicate {
	return c.predicate("<=", string(value), "")
}
func (c PostgresRecordClockColumn) Gt(value string) PostgresRecordPredicate {
	return c.predicate(">", string(value), "")
}
func (c PostgresRecordClockColumn) Ge(value string) PostgresRecordPredicate {
	return c.predicate(">=", string(value), "")
}
func (c PostgresRecordClockColumn) In(values ...string) PostgresRecordPredicate {
	args := make([]any, len(values))
	for i, v := range values {
		args[i] = string(v)
	}
	return c.predicate("in", args, "")
}

type PostgresRecordComputedColumn struct{ valid bool }

func (PostgresRecordComputedColumn) String() string { return "goquent: generated details omitted" }
func (PostgresRecordComputedColumn) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (PostgresRecordComputedColumn) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c PostgresRecordComputedColumn) predicate(op string, value any, ref string) PostgresRecordPredicate {
	if !c.valid {
		return PostgresRecordPredicate{}
	}
	return PostgresRecordPredicate{filter: operation.FilterSpec{Field: "computed", Op: op, Value: value, ValueRef: ref}}
}
func (c PostgresRecordComputedColumn) Asc() PostgresRecordOrder {
	if !c.valid {
		return PostgresRecordOrder{}
	}
	return PostgresRecordOrder{order: operation.OrderSpec{Field: "computed", Direction: "asc"}}
}
func (c PostgresRecordComputedColumn) Desc() PostgresRecordOrder {
	if !c.valid {
		return PostgresRecordOrder{}
	}
	return PostgresRecordOrder{order: operation.OrderSpec{Field: "computed", Direction: "desc"}}
}
func (c PostgresRecordComputedColumn) IsNull() PostgresRecordPredicate {
	return c.predicate("is_null", nil, "")
}
func (c PostgresRecordComputedColumn) IsNotNull() PostgresRecordPredicate {
	return c.predicate("is_not_null", nil, "")
}
func (c PostgresRecordComputedColumn) Eq(value int32) PostgresRecordPredicate {
	return c.predicate("=", int32(value), "")
}
func (c PostgresRecordComputedColumn) Ne(value int32) PostgresRecordPredicate {
	return c.predicate("!=", int32(value), "")
}
func (c PostgresRecordComputedColumn) Lt(value int32) PostgresRecordPredicate {
	return c.predicate("<", int32(value), "")
}
func (c PostgresRecordComputedColumn) Le(value int32) PostgresRecordPredicate {
	return c.predicate("<=", int32(value), "")
}
func (c PostgresRecordComputedColumn) Gt(value int32) PostgresRecordPredicate {
	return c.predicate(">", int32(value), "")
}
func (c PostgresRecordComputedColumn) Ge(value int32) PostgresRecordPredicate {
	return c.predicate(">=", int32(value), "")
}
func (c PostgresRecordComputedColumn) In(values ...int32) PostgresRecordPredicate {
	args := make([]any, len(values))
	for i, v := range values {
		args[i] = int32(v)
	}
	return c.predicate("in", args, "")
}

type PostgresRecordFlagColumn struct{ valid bool }

func (PostgresRecordFlagColumn) String() string { return "goquent: generated details omitted" }
func (PostgresRecordFlagColumn) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (PostgresRecordFlagColumn) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c PostgresRecordFlagColumn) predicate(op string, value any, ref string) PostgresRecordPredicate {
	if !c.valid {
		return PostgresRecordPredicate{}
	}
	return PostgresRecordPredicate{filter: operation.FilterSpec{Field: "flag", Op: op, Value: value, ValueRef: ref}}
}
func (c PostgresRecordFlagColumn) Asc() PostgresRecordOrder {
	if !c.valid {
		return PostgresRecordOrder{}
	}
	return PostgresRecordOrder{order: operation.OrderSpec{Field: "flag", Direction: "asc"}}
}
func (c PostgresRecordFlagColumn) Desc() PostgresRecordOrder {
	if !c.valid {
		return PostgresRecordOrder{}
	}
	return PostgresRecordOrder{order: operation.OrderSpec{Field: "flag", Direction: "desc"}}
}
func (c PostgresRecordFlagColumn) IsNull() PostgresRecordPredicate {
	return c.predicate("is_null", nil, "")
}
func (c PostgresRecordFlagColumn) IsNotNull() PostgresRecordPredicate {
	return c.predicate("is_not_null", nil, "")
}
func (c PostgresRecordFlagColumn) Eq(value bool) PostgresRecordPredicate {
	return c.predicate("=", bool(value), "")
}
func (c PostgresRecordFlagColumn) Ne(value bool) PostgresRecordPredicate {
	return c.predicate("!=", bool(value), "")
}
func (c PostgresRecordFlagColumn) In(values ...bool) PostgresRecordPredicate {
	args := make([]any, len(values))
	for i, v := range values {
		args[i] = bool(v)
	}
	return c.predicate("in", args, "")
}

type PostgresRecordHappenedColumn struct{ valid bool }

func (PostgresRecordHappenedColumn) String() string { return "goquent: generated details omitted" }
func (PostgresRecordHappenedColumn) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (PostgresRecordHappenedColumn) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c PostgresRecordHappenedColumn) predicate(op string, value any, ref string) PostgresRecordPredicate {
	if !c.valid {
		return PostgresRecordPredicate{}
	}
	return PostgresRecordPredicate{filter: operation.FilterSpec{Field: "happened", Op: op, Value: value, ValueRef: ref}}
}
func (c PostgresRecordHappenedColumn) Asc() PostgresRecordOrder {
	if !c.valid {
		return PostgresRecordOrder{}
	}
	return PostgresRecordOrder{order: operation.OrderSpec{Field: "happened", Direction: "asc"}}
}
func (c PostgresRecordHappenedColumn) Desc() PostgresRecordOrder {
	if !c.valid {
		return PostgresRecordOrder{}
	}
	return PostgresRecordOrder{order: operation.OrderSpec{Field: "happened", Direction: "desc"}}
}
func (c PostgresRecordHappenedColumn) IsNull() PostgresRecordPredicate {
	return c.predicate("is_null", nil, "")
}
func (c PostgresRecordHappenedColumn) IsNotNull() PostgresRecordPredicate {
	return c.predicate("is_not_null", nil, "")
}
func (c PostgresRecordHappenedColumn) Eq(value string) PostgresRecordPredicate {
	return c.predicate("=", string(value), "")
}
func (c PostgresRecordHappenedColumn) Ne(value string) PostgresRecordPredicate {
	return c.predicate("!=", string(value), "")
}
func (c PostgresRecordHappenedColumn) Lt(value string) PostgresRecordPredicate {
	return c.predicate("<", string(value), "")
}
func (c PostgresRecordHappenedColumn) Le(value string) PostgresRecordPredicate {
	return c.predicate("<=", string(value), "")
}
func (c PostgresRecordHappenedColumn) Gt(value string) PostgresRecordPredicate {
	return c.predicate(">", string(value), "")
}
func (c PostgresRecordHappenedColumn) Ge(value string) PostgresRecordPredicate {
	return c.predicate(">=", string(value), "")
}
func (c PostgresRecordHappenedColumn) In(values ...string) PostgresRecordPredicate {
	args := make([]any, len(values))
	for i, v := range values {
		args[i] = string(v)
	}
	return c.predicate("in", args, "")
}

type PostgresRecordIDKey int64

func (PostgresRecordIDKey) String() string { return "goquent: generated details omitted" }
func (PostgresRecordIDKey) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (PostgresRecordIDKey) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}

type PostgresRecordIDColumn struct{ valid bool }

func (PostgresRecordIDColumn) String() string { return "goquent: generated details omitted" }
func (PostgresRecordIDColumn) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (PostgresRecordIDColumn) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c PostgresRecordIDColumn) predicate(op string, value any, ref string) PostgresRecordPredicate {
	if !c.valid {
		return PostgresRecordPredicate{}
	}
	return PostgresRecordPredicate{filter: operation.FilterSpec{Field: "id", Op: op, Value: value, ValueRef: ref}}
}
func (c PostgresRecordIDColumn) Asc() PostgresRecordOrder {
	if !c.valid {
		return PostgresRecordOrder{}
	}
	return PostgresRecordOrder{order: operation.OrderSpec{Field: "id", Direction: "asc"}}
}
func (c PostgresRecordIDColumn) Desc() PostgresRecordOrder {
	if !c.valid {
		return PostgresRecordOrder{}
	}
	return PostgresRecordOrder{order: operation.OrderSpec{Field: "id", Direction: "desc"}}
}
func (c PostgresRecordIDColumn) IsNull() PostgresRecordPredicate {
	return c.predicate("is_null", nil, "")
}
func (c PostgresRecordIDColumn) IsNotNull() PostgresRecordPredicate {
	return c.predicate("is_not_null", nil, "")
}
func (c PostgresRecordIDColumn) Eq(value PostgresRecordIDKey) PostgresRecordPredicate {
	return c.predicate("=", int64(value), "")
}
func (c PostgresRecordIDColumn) Ne(value PostgresRecordIDKey) PostgresRecordPredicate {
	return c.predicate("!=", int64(value), "")
}
func (c PostgresRecordIDColumn) Lt(value PostgresRecordIDKey) PostgresRecordPredicate {
	return c.predicate("<", int64(value), "")
}
func (c PostgresRecordIDColumn) Le(value PostgresRecordIDKey) PostgresRecordPredicate {
	return c.predicate("<=", int64(value), "")
}
func (c PostgresRecordIDColumn) Gt(value PostgresRecordIDKey) PostgresRecordPredicate {
	return c.predicate(">", int64(value), "")
}
func (c PostgresRecordIDColumn) Ge(value PostgresRecordIDKey) PostgresRecordPredicate {
	return c.predicate(">=", int64(value), "")
}
func (c PostgresRecordIDColumn) In(values ...PostgresRecordIDKey) PostgresRecordPredicate {
	args := make([]any, len(values))
	for i, v := range values {
		args[i] = int64(v)
	}
	return c.predicate("in", args, "")
}

type PostgresRecordImmutableColumn struct{ valid bool }

func (PostgresRecordImmutableColumn) String() string { return "goquent: generated details omitted" }
func (PostgresRecordImmutableColumn) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (PostgresRecordImmutableColumn) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c PostgresRecordImmutableColumn) predicate(op string, value any, ref string) PostgresRecordPredicate {
	if !c.valid {
		return PostgresRecordPredicate{}
	}
	return PostgresRecordPredicate{filter: operation.FilterSpec{Field: "immutable", Op: op, Value: value, ValueRef: ref}}
}
func (c PostgresRecordImmutableColumn) Asc() PostgresRecordOrder {
	if !c.valid {
		return PostgresRecordOrder{}
	}
	return PostgresRecordOrder{order: operation.OrderSpec{Field: "immutable", Direction: "asc"}}
}
func (c PostgresRecordImmutableColumn) Desc() PostgresRecordOrder {
	if !c.valid {
		return PostgresRecordOrder{}
	}
	return PostgresRecordOrder{order: operation.OrderSpec{Field: "immutable", Direction: "desc"}}
}
func (c PostgresRecordImmutableColumn) IsNull() PostgresRecordPredicate {
	return c.predicate("is_null", nil, "")
}
func (c PostgresRecordImmutableColumn) IsNotNull() PostgresRecordPredicate {
	return c.predicate("is_not_null", nil, "")
}
func (c PostgresRecordImmutableColumn) Eq(value string) PostgresRecordPredicate {
	return c.predicate("=", string(value), "")
}
func (c PostgresRecordImmutableColumn) Ne(value string) PostgresRecordPredicate {
	return c.predicate("!=", string(value), "")
}
func (c PostgresRecordImmutableColumn) Lt(value string) PostgresRecordPredicate {
	return c.predicate("<", string(value), "")
}
func (c PostgresRecordImmutableColumn) Le(value string) PostgresRecordPredicate {
	return c.predicate("<=", string(value), "")
}
func (c PostgresRecordImmutableColumn) Gt(value string) PostgresRecordPredicate {
	return c.predicate(">", string(value), "")
}
func (c PostgresRecordImmutableColumn) Ge(value string) PostgresRecordPredicate {
	return c.predicate(">=", string(value), "")
}
func (c PostgresRecordImmutableColumn) Like(value string) PostgresRecordPredicate {
	return c.predicate("like", string(value), "")
}
func (c PostgresRecordImmutableColumn) In(values ...string) PostgresRecordPredicate {
	args := make([]any, len(values))
	for i, v := range values {
		args[i] = string(v)
	}
	return c.predicate("in", args, "")
}

type PostgresRecordNoteColumn struct{ valid bool }

func (PostgresRecordNoteColumn) String() string { return "goquent: generated details omitted" }
func (PostgresRecordNoteColumn) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (PostgresRecordNoteColumn) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c PostgresRecordNoteColumn) predicate(op string, value any, ref string) PostgresRecordPredicate {
	if !c.valid {
		return PostgresRecordPredicate{}
	}
	return PostgresRecordPredicate{filter: operation.FilterSpec{Field: "note", Op: op, Value: value, ValueRef: ref}}
}
func (c PostgresRecordNoteColumn) Asc() PostgresRecordOrder {
	if !c.valid {
		return PostgresRecordOrder{}
	}
	return PostgresRecordOrder{order: operation.OrderSpec{Field: "note", Direction: "asc"}}
}
func (c PostgresRecordNoteColumn) Desc() PostgresRecordOrder {
	if !c.valid {
		return PostgresRecordOrder{}
	}
	return PostgresRecordOrder{order: operation.OrderSpec{Field: "note", Direction: "desc"}}
}
func (c PostgresRecordNoteColumn) IsNull() PostgresRecordPredicate {
	return c.predicate("is_null", nil, "")
}
func (c PostgresRecordNoteColumn) IsNotNull() PostgresRecordPredicate {
	return c.predicate("is_not_null", nil, "")
}
func (c PostgresRecordNoteColumn) Eq(value string) PostgresRecordPredicate {
	return c.predicate("=", string(value), "")
}
func (c PostgresRecordNoteColumn) Ne(value string) PostgresRecordPredicate {
	return c.predicate("!=", string(value), "")
}
func (c PostgresRecordNoteColumn) Lt(value string) PostgresRecordPredicate {
	return c.predicate("<", string(value), "")
}
func (c PostgresRecordNoteColumn) Le(value string) PostgresRecordPredicate {
	return c.predicate("<=", string(value), "")
}
func (c PostgresRecordNoteColumn) Gt(value string) PostgresRecordPredicate {
	return c.predicate(">", string(value), "")
}
func (c PostgresRecordNoteColumn) Ge(value string) PostgresRecordPredicate {
	return c.predicate(">=", string(value), "")
}
func (c PostgresRecordNoteColumn) Like(value string) PostgresRecordPredicate {
	return c.predicate("like", string(value), "")
}
func (c PostgresRecordNoteColumn) In(values ...string) PostgresRecordPredicate {
	args := make([]any, len(values))
	for i, v := range values {
		args[i] = string(v)
	}
	return c.predicate("in", args, "")
}

type PostgresRecordSegmentKey int32

func (PostgresRecordSegmentKey) String() string { return "goquent: generated details omitted" }
func (PostgresRecordSegmentKey) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (PostgresRecordSegmentKey) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}

type PostgresRecordSegmentColumn struct{ valid bool }

func (PostgresRecordSegmentColumn) String() string { return "goquent: generated details omitted" }
func (PostgresRecordSegmentColumn) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (PostgresRecordSegmentColumn) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c PostgresRecordSegmentColumn) predicate(op string, value any, ref string) PostgresRecordPredicate {
	if !c.valid {
		return PostgresRecordPredicate{}
	}
	return PostgresRecordPredicate{filter: operation.FilterSpec{Field: "segment", Op: op, Value: value, ValueRef: ref}}
}
func (c PostgresRecordSegmentColumn) Asc() PostgresRecordOrder {
	if !c.valid {
		return PostgresRecordOrder{}
	}
	return PostgresRecordOrder{order: operation.OrderSpec{Field: "segment", Direction: "asc"}}
}
func (c PostgresRecordSegmentColumn) Desc() PostgresRecordOrder {
	if !c.valid {
		return PostgresRecordOrder{}
	}
	return PostgresRecordOrder{order: operation.OrderSpec{Field: "segment", Direction: "desc"}}
}
func (c PostgresRecordSegmentColumn) IsNull() PostgresRecordPredicate {
	return c.predicate("is_null", nil, "")
}
func (c PostgresRecordSegmentColumn) IsNotNull() PostgresRecordPredicate {
	return c.predicate("is_not_null", nil, "")
}
func (c PostgresRecordSegmentColumn) Eq(value PostgresRecordSegmentKey) PostgresRecordPredicate {
	return c.predicate("=", int32(value), "")
}
func (c PostgresRecordSegmentColumn) Ne(value PostgresRecordSegmentKey) PostgresRecordPredicate {
	return c.predicate("!=", int32(value), "")
}
func (c PostgresRecordSegmentColumn) Lt(value PostgresRecordSegmentKey) PostgresRecordPredicate {
	return c.predicate("<", int32(value), "")
}
func (c PostgresRecordSegmentColumn) Le(value PostgresRecordSegmentKey) PostgresRecordPredicate {
	return c.predicate("<=", int32(value), "")
}
func (c PostgresRecordSegmentColumn) Gt(value PostgresRecordSegmentKey) PostgresRecordPredicate {
	return c.predicate(">", int32(value), "")
}
func (c PostgresRecordSegmentColumn) Ge(value PostgresRecordSegmentKey) PostgresRecordPredicate {
	return c.predicate(">=", int32(value), "")
}
func (c PostgresRecordSegmentColumn) In(values ...PostgresRecordSegmentKey) PostgresRecordPredicate {
	args := make([]any, len(values))
	for i, v := range values {
		args[i] = int32(v)
	}
	return c.predicate("in", args, "")
}

type PostgresRecordStampColumn struct{ valid bool }

func (PostgresRecordStampColumn) String() string { return "goquent: generated details omitted" }
func (PostgresRecordStampColumn) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (PostgresRecordStampColumn) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c PostgresRecordStampColumn) predicate(op string, value any, ref string) PostgresRecordPredicate {
	if !c.valid {
		return PostgresRecordPredicate{}
	}
	return PostgresRecordPredicate{filter: operation.FilterSpec{Field: "stamp", Op: op, Value: value, ValueRef: ref}}
}
func (c PostgresRecordStampColumn) Asc() PostgresRecordOrder {
	if !c.valid {
		return PostgresRecordOrder{}
	}
	return PostgresRecordOrder{order: operation.OrderSpec{Field: "stamp", Direction: "asc"}}
}
func (c PostgresRecordStampColumn) Desc() PostgresRecordOrder {
	if !c.valid {
		return PostgresRecordOrder{}
	}
	return PostgresRecordOrder{order: operation.OrderSpec{Field: "stamp", Direction: "desc"}}
}
func (c PostgresRecordStampColumn) IsNull() PostgresRecordPredicate {
	return c.predicate("is_null", nil, "")
}
func (c PostgresRecordStampColumn) IsNotNull() PostgresRecordPredicate {
	return c.predicate("is_not_null", nil, "")
}
func (c PostgresRecordStampColumn) Eq(value string) PostgresRecordPredicate {
	return c.predicate("=", string(value), "")
}
func (c PostgresRecordStampColumn) Ne(value string) PostgresRecordPredicate {
	return c.predicate("!=", string(value), "")
}
func (c PostgresRecordStampColumn) Lt(value string) PostgresRecordPredicate {
	return c.predicate("<", string(value), "")
}
func (c PostgresRecordStampColumn) Le(value string) PostgresRecordPredicate {
	return c.predicate("<=", string(value), "")
}
func (c PostgresRecordStampColumn) Gt(value string) PostgresRecordPredicate {
	return c.predicate(">", string(value), "")
}
func (c PostgresRecordStampColumn) Ge(value string) PostgresRecordPredicate {
	return c.predicate(">=", string(value), "")
}
func (c PostgresRecordStampColumn) In(values ...string) PostgresRecordPredicate {
	args := make([]any, len(values))
	for i, v := range values {
		args[i] = string(v)
	}
	return c.predicate("in", args, "")
}

type PostgresRecordStatusValue string

func (PostgresRecordStatusValue) String() string { return "goquent: generated details omitted" }
func (PostgresRecordStatusValue) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (PostgresRecordStatusValue) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}

const PostgresRecordStatusValueChoice1 PostgresRecordStatusValue = "ready"
const PostgresRecordStatusValueChoice2 PostgresRecordStatusValue = "closed"
const PostgresRecordStatusValueChoice3 PostgresRecordStatusValue = "a-b"
const PostgresRecordStatusValueChoice4 PostgresRecordStatusValue = "a_b"
const PostgresRecordStatusValueChoice5 PostgresRecordStatusValue = "type"

type PostgresRecordStatusColumn struct{ valid bool }

func (PostgresRecordStatusColumn) String() string { return "goquent: generated details omitted" }
func (PostgresRecordStatusColumn) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (PostgresRecordStatusColumn) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (c PostgresRecordStatusColumn) predicate(op string, value any, ref string) PostgresRecordPredicate {
	if !c.valid {
		return PostgresRecordPredicate{}
	}
	return PostgresRecordPredicate{filter: operation.FilterSpec{Field: "status", Op: op, Value: value, ValueRef: ref}}
}
func (c PostgresRecordStatusColumn) Asc() PostgresRecordOrder {
	if !c.valid {
		return PostgresRecordOrder{}
	}
	return PostgresRecordOrder{order: operation.OrderSpec{Field: "status", Direction: "asc"}}
}
func (c PostgresRecordStatusColumn) Desc() PostgresRecordOrder {
	if !c.valid {
		return PostgresRecordOrder{}
	}
	return PostgresRecordOrder{order: operation.OrderSpec{Field: "status", Direction: "desc"}}
}
func (c PostgresRecordStatusColumn) IsNull() PostgresRecordPredicate {
	return c.predicate("is_null", nil, "")
}
func (c PostgresRecordStatusColumn) IsNotNull() PostgresRecordPredicate {
	return c.predicate("is_not_null", nil, "")
}
func (c PostgresRecordStatusColumn) Eq(value PostgresRecordStatusValue) PostgresRecordPredicate {
	return c.predicate("=", string(value), "")
}
func (c PostgresRecordStatusColumn) Ne(value PostgresRecordStatusValue) PostgresRecordPredicate {
	return c.predicate("!=", string(value), "")
}
func (c PostgresRecordStatusColumn) Lt(value PostgresRecordStatusValue) PostgresRecordPredicate {
	return c.predicate("<", string(value), "")
}
func (c PostgresRecordStatusColumn) Le(value PostgresRecordStatusValue) PostgresRecordPredicate {
	return c.predicate("<=", string(value), "")
}
func (c PostgresRecordStatusColumn) Gt(value PostgresRecordStatusValue) PostgresRecordPredicate {
	return c.predicate(">", string(value), "")
}
func (c PostgresRecordStatusColumn) Ge(value PostgresRecordStatusValue) PostgresRecordPredicate {
	return c.predicate(">=", string(value), "")
}
func (c PostgresRecordStatusColumn) Like(value PostgresRecordStatusValue) PostgresRecordPredicate {
	return c.predicate("like", string(value), "")
}
func (c PostgresRecordStatusColumn) In(values ...PostgresRecordStatusValue) PostgresRecordPredicate {
	args := make([]any, len(values))
	for i, v := range values {
		args[i] = string(v)
	}
	return c.predicate("in", args, "")
}

type PostgresRecordSummaryRow struct {
	ID       int64                  `db:"id"`
	Segment  int32                  `db:"segment"`
	Status   string                 `db:"status"`
	Active   bool                   `db:"active"`
	Flag     sql.NullBool           `db:"flag"`
	Note     sql.Null[string]       `db:"note"`
	Balance  string                 `db:"balance"`
	Happened time.Time              `db:"happened"`
	Clock    PostgresRecordTimeText `db:"clock"`
	Stamp    time.Time              `db:"stamp"`
}

func (PostgresRecordSummaryRow) String() string { return "goquent: generated details omitted" }
func (PostgresRecordSummaryRow) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (PostgresRecordSummaryRow) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (r *PostgresRecordRepository) PlanSummary(ctx context.Context, input PostgresRecordRead) (*orm.QueryPlan, operation.DiagnosticView, error) {
	return r.db.CompileOperationWithDiagnostics(ctx, input.spec([]string{"id", "segment", "status", "active", "flag", "note", "balance", "happened", "clock", "stamp"}), operation.Options{Manifest: postgresRecordSnapshot()})
}
func (r *PostgresRecordRepository) SelectSummary(ctx context.Context, input PostgresRecordRead) ([]PostgresRecordSummaryRow, error) {
	return orm.SelectOperationBy[PostgresRecordSummaryRow](ctx, r.db, input.spec([]string{"id", "segment", "status", "active", "flag", "note", "balance", "happened", "clock", "stamp"}), operation.Options{Manifest: postgresRecordSnapshot()})
}

type PostgresRecordIdentityRow struct {
	Segment int32 `db:"segment"`
	ID      int64 `db:"id"`
}

func (PostgresRecordIdentityRow) String() string { return "goquent: generated details omitted" }
func (PostgresRecordIdentityRow) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (PostgresRecordIdentityRow) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func (r *PostgresRecordRepository) PlanIdentity(ctx context.Context, input PostgresRecordRead) (*orm.QueryPlan, operation.DiagnosticView, error) {
	return r.db.CompileOperationWithDiagnostics(ctx, input.spec([]string{"segment", "id"}), operation.Options{Manifest: postgresRecordSnapshot()})
}
func (r *PostgresRecordRepository) SelectIdentity(ctx context.Context, input PostgresRecordRead) ([]PostgresRecordIdentityRow, error) {
	return orm.SelectOperationBy[PostgresRecordIdentityRow](ctx, r.db, input.spec([]string{"segment", "id"}), operation.Options{Manifest: postgresRecordSnapshot()})
}

type PostgresRecordKey struct {
	ID      PostgresRecordIDKey
	Segment PostgresRecordSegmentKey
}

func (PostgresRecordKey) String() string { return "goquent: generated details omitted" }
func (PostgresRecordKey) Format(s fmt.State, verb rune) {
	_, _ = s.Write([]byte("goquent: generated details omitted"))
}
func (PostgresRecordKey) MarshalJSON() ([]byte, error) {
	return []byte("{\"details_omitted\":true}"), nil
}
func postgresRecordKeyInput(key PostgresRecordKey, input PostgresRecordRead) PostgresRecordRead {
	input.Filters = append([]PostgresRecordPredicate(nil), input.Filters...)
	cols := PostgresRecordColumns()
	input.Filters = append(input.Filters, cols.ID.Eq(key.ID))
	input.Filters = append(input.Filters, cols.Segment.Eq(key.Segment))
	return input
}
func (r *PostgresRecordRepository) PlanFindByKey(ctx context.Context, key PostgresRecordKey, input PostgresRecordRead) (*orm.QueryPlan, operation.DiagnosticView, error) {
	input = postgresRecordKeyInput(key, input)
	return r.db.CompileOperationWithDiagnostics(ctx, input.spec([]string{"active", "balance", "clock", "computed", "flag", "happened", "id", "immutable", "note", "segment", "stamp", "status"}), operation.Options{Manifest: postgresRecordSnapshot()})
}
func (r *PostgresRecordRepository) FindByKey(ctx context.Context, key PostgresRecordKey, input PostgresRecordRead) (PostgresRecordRow, error) {
	input = postgresRecordKeyInput(key, input)
	rows, err := orm.SelectOperationBy[PostgresRecordRow](ctx, r.db, input.spec([]string{"active", "balance", "clock", "computed", "flag", "happened", "id", "immutable", "note", "segment", "stamp", "status"}), operation.Options{Manifest: postgresRecordSnapshot()})
	if err != nil {
		return PostgresRecordRow{}, err
	}
	if len(rows) == 0 {
		return PostgresRecordRow{}, orm.ErrNotFound
	}
	return rows[0], nil
}
