package publicview

// Code is a fixed cross-package display vocabulary, not a rule registry.
func Code(s string) string {
	switch s {
	case "BULK_DELETE_DETECTED":
		return "BULK_DELETE_DETECTED"
	case "BULK_UPDATE_DETECTED":
		return "BULK_UPDATE_DETECTED"
	case "DELETE_WITHOUT_WHERE":
		return "DELETE_WITHOUT_WHERE"
	case "DESTRUCTIVE_SQL_DETECTED":
		return "DESTRUCTIVE_SQL_DETECTED"
	case "LIMIT_MISSING":
		return "LIMIT_MISSING"
	case "MANIFEST_REQUIRED":
		return "MANIFEST_REQUIRED"
	case "MANIFEST_STALE":
		return "MANIFEST_STALE"
	case "MANIFEST_UNREADABLE":
		return "MANIFEST_UNREADABLE"
	case "MANIFEST_UNVERIFIED":
		return "MANIFEST_UNVERIFIED"
	case "MIGRATION_ADD_INDEX_NON_CONCURRENT":
		return "MIGRATION_ADD_INDEX_NON_CONCURRENT"
	case "MIGRATION_ADD_NOT_NULL_COLUMN":
		return "MIGRATION_ADD_NOT_NULL_COLUMN"
	case "MIGRATION_ALTER_COLUMN_TYPE":
		return "MIGRATION_ALTER_COLUMN_TYPE"
	case "MIGRATION_BACKFILL_REVIEW":
		return "MIGRATION_BACKFILL_REVIEW"
	case "MIGRATION_DROP_COLUMN":
		return "MIGRATION_DROP_COLUMN"
	case "MIGRATION_DROP_INDEX":
		return "MIGRATION_DROP_INDEX"
	case "MIGRATION_DROP_TABLE":
		return "MIGRATION_DROP_TABLE"
	case "MIGRATION_RENAME_COLUMN":
		return "MIGRATION_RENAME_COLUMN"
	case "MIGRATION_SET_NOT_NULL":
		return "MIGRATION_SET_NOT_NULL"
	case "MIGRATION_TYPE_NARROWING":
		return "MIGRATION_TYPE_NARROWING"
	case "MIGRATION_UNSUPPORTED":
		return "MIGRATION_UNSUPPORTED"
	case "OPERATION_SPEC_PII_SELECTED":
		return "OPERATION_SPEC_PII_SELECTED"
	case "OPERATION_SPEC_REQUIRED_FILTER_MISSING":
		return "OPERATION_SPEC_REQUIRED_FILTER_MISSING"
	case "PII_COLUMN_SELECTED":
		return "PII_COLUMN_SELECTED"
	case "RAW_SQL_USED":
		return "RAW_SQL_USED"
	case "REQUIRED_FILTER_MISSING":
		return "REQUIRED_FILTER_MISSING"
	case "REQUIRED_PREDICATE_MISSING":
		return "REQUIRED_PREDICATE_MISSING"
	case "SELECT_STAR_USED":
		return "SELECT_STAR_USED"
	case "SOFT_DELETE_FILTER_MISSING":
		return "SOFT_DELETE_FILTER_MISSING"
	case "STATIC_REVIEW_PARTIAL":
		return "STATIC_REVIEW_PARTIAL"
	case "STATIC_REVIEW_UNSUPPORTED":
		return "STATIC_REVIEW_UNSUPPORTED"
	case "SUPPRESSION_CONFIG_INVALID":
		return "SUPPRESSION_CONFIG_INVALID"
	case "SUPPRESSION_EXPIRED":
		return "SUPPRESSION_EXPIRED"
	case "SUPPRESSION_NOT_ALLOWED":
		return "SUPPRESSION_NOT_ALLOWED"
	case "SUPPRESSION_OVERBROAD":
		return "SUPPRESSION_OVERBROAD"
	case "SUPPRESSION_OWNER_MISSING":
		return "SUPPRESSION_OWNER_MISSING"
	case "SUPPRESSION_REASON_WEAK":
		return "SUPPRESSION_REASON_WEAK"
	case "SUPPRESSION_UNUSED":
		return "SUPPRESSION_UNUSED"
	case "TENANT_FILTER_MISSING":
		return "TENANT_FILTER_MISSING"
	case "TENANT_POLICY_REJECTED":
		return "TENANT_POLICY_REJECTED"
	case "UNSUPPORTED_RISK_ENGINE":
		return "UNSUPPORTED_RISK_ENGINE"
	case "UPDATE_WITHOUT_WHERE":
		return "UPDATE_WITHOUT_WHERE"
	case "WEAK_PREDICATE":
		return "WEAK_PREDICATE"
	}
	return "unknown"
}

// Message never reuses source diagnostic text.
func Message(code string) string {
	c := Code(code)
	if c == "unknown" {
		return "Unknown diagnostic; details omitted."
	}
	return c + ": diagnostic details omitted."
}
